// The knowledge base as context for a live meeting: which pages get picked,
// what fits, and — the part that matters most — what the model is allowed to
// believe it was given. See meetingContext.test.js for the pinned contract;
// its comments explain WHY, not just what.
//
// THE BUG THIS FILE EXISTS TO PREVENT: lib/experience/pageContext.js's
// formatAttachment disclaims "contents not read" for slides/sheets/archives
// only, and deliberately says nothing for images, PDFs or text files —
// because in the Ask AI flow those three really are downloaded and attached
// to the SAME request. Silence there means "the bytes were sent". A meeting
// read sends no bytes at all, ever — reusing formatAttachment (correct, and
// required: a second copy of its rules is how they drift) inherits that
// silence into a flow where it is false. Nothing throws, nothing looks
// wrong; the model is simply handed `- Q3 board deck.pdf (PDF) - notes:
// revenue slide` and will say, out loud, in a real meeting, "your board deck
// shows revenue up 12%." So this file adds ONE blanket sentence, present
// whenever any attachment is listed at all, stating plainly that no
// attachment bytes were read this call.
//
// Eligibility here is deliberately narrower than lib/copilot/projectStories.js:
// that module also excludes any page with `generated_kind` set (a model's own
// prior claims should never be replayed as the candidate's lived experience).
// A meeting page is different — the user directed that a page they recorded,
// or any other page in their tree, IS their own experience regardless of how
// it was created, so eligibility here turns on archived-or-not and nothing
// else. See the "INCLUDES a page that was generated by another feature" test.

import { formatAttachment } from "@/lib/experience/pageContext.js";
import { rankPagesByRelevance } from "@/lib/experience/knowledgeBase.js";
import { MEETING_LABELS } from "./insightContract.js";

export const MAX_MEETING_CONTEXT_CHARS = 9000;

// How many of ONE page's attachments get a line before the rest are counted
// in the notice instead. Mirrors lib/experience/pageContext.js's own
// MAX_LISTED_ATTACHMENTS, at a smaller number because the budget here is
// smaller (9000 chars across the WHOLE knowledge base, against 12000 for a
// single page there). Now that real rows reach this module from the
// database — app/api/meeting/insights/route.js fetches them — one page with
// an unreasonable number of files could otherwise spend the entire page
// budget on an inventory and stop the packing loop at page one.
export const MAX_LISTED_ATTACHMENTS = 20;

// Reserved out of the budget for the three notices (attachment honesty +
// unlisted-attachment count + dropped-page count), assembled LAST after the page blocks are already
// sized — sized generously above the worst realistic combined notice length
// so the notices themselves are never what gets cut. Mirrors the same
// pattern in lib/experience/pageContext.js and lib/copilot/projectStories.js.
const NOTICE_RESERVE_CHARS = 400;

const SEPARATOR = "\n\n---\n\n";

// The exact sentence meetingContext.test.js's "the attachment honesty claim"
// block and app/api/meeting/insights/route.test.js's "tells the model
// plainly that it read no attachment bytes" both key off of
// (case-insensitively). Written once, here, so no caller can restate it
// slightly differently and drift.
const NO_ATTACHMENT_BYTES_NOTICE =
  "No attachment file contents were read for this meeting — only the file names and any saved notes above were seen.";

function str(value) {
  return typeof value === "string" ? value : "";
}

function pluralize(count, noun) {
  return `${count} ${noun}${count === 1 ? "" : "s"}`;
}

// A "page" is usable input at all only once it has a real string id. This is
// the one thing standing between "survives a page list full of junk" and a
// bare `{}` slipping through every later check (typeof {} === "object" and
// {}.archived_at is undefined, so an eligibility check alone would happily
// accept it) and surfacing as an included page whose id is the string
// "undefined" reaching the client.
function isUsablePage(page) {
  return !!page && typeof page === "object" && typeof page.id === "string" && page.id.trim() !== "";
}

// Eligibility, and ONLY eligibility, per this file's header comment:
// archived or not, nothing else. Exported so lib/meeting/insightsLocal.js —
// which independently decides which pages are worth surfacing an insight
// about — filters against the exact same rule rather than growing a second,
// driftable copy of it.
export function isEligibleMeetingPage(page) {
  if (!isUsablePage(page)) return false;
  return page.archived_at === null || page.archived_at === undefined;
}

// The speaker prefixes the capture layer writes into a transcript ("You: ",
// "Others: "), built off insightContract.js's MEETING_LABELS rather than a
// second hard-coded "you|others" — that module is explicitly the one place
// speaker-routing values become display copy. The empty "room" label needs
// no stripping: a single shared-room mic has no prefix to strip.
const SPEAKER_PREFIXES = Object.values(MEETING_LABELS).filter(Boolean);
const SPEAKER_PREFIX_RE = new RegExp(`^(?:${SPEAKER_PREFIXES.join("|")})\\s*:\\s*`, "i");

// Drops the speaker label from every line of a transcript, returning the
// spoken words alone (blank lines removed).
//
// WHY THIS EXISTS: every relevance heuristic in the meeting copilot — this
// module's page ranking and lib/meeting/insightsLocal.js's topic terms and
// page scoring alike — tokenises on /[a-z0-9]{4,}/, and "others" clears that
// bar. In any call-mode meeting "Others" is the single most frequent token
// in the whole transcript by a wide margin, so left in place it becomes the
// top "topic term" and it scores any page containing the word "others"
// above zero — surfacing a page whose ONLY overlap with the conversation is
// a label this app itself wrote.
//
// WHY IT LIVES HERE rather than in insightsLocal.js: that module already
// imports isEligibleMeetingPage from this one, so this is the direction the
// dependency already runs. One copy, imported by both, so the two rankings
// can never disagree about what counts as meeting content.
export function stripSpeakerLabels(transcript) {
  return String(transcript || "")
    .split(/\r?\n/)
    .map((line) => line.replace(SPEAKER_PREFIX_RE, "").trim())
    .filter(Boolean)
    .join("\n");
}

// Ranks pages by term overlap against `queryText`, ties broken by the page's
// own `position` (falling back to array order when position is missing —
// Array.prototype.sort has been stable since ES2019, so pages tied on both
// score and position simply keep the order they arrived in). Does NOT filter
// for eligibility itself — callers pass in whatever set they've already
// decided is in play (buildMeetingContext excludes the pinned page before
// calling this; lib/meeting/insightsLocal.js has its own top-N cutoff on top
// of this ranking).
//
// Delegates to lib/experience/knowledgeBase.js's rankPagesByRelevance
// (ARCH §4c): the two modules used to carry two identical twelve-line
// functions, which is a WISH that "the meeting and interview surfaces can
// never disagree about what counts as relevant" — not a fact. One function,
// imported by both, makes it a fact instead. Verified byte-identical
// against this function's own prior body before the delegation was made:
// same overlap-score-desc ordering, same position-else-index tie-break,
// same stability guarantee. lib/meeting/insightsLocal.js's own import of
// rankMeetingPages is unaffected — it still gets the same named export.
export const rankMeetingPages = rankPagesByRelevance;

// One page's whole-page block: a heading carrying both the title (what a
// human — or the notice below — refers to it by) and the page's own id
// (what a model citing it back via insightContract.js's `source: { kind:
// "page", pageId }` must use), the attachment inventory when there is one,
// then the raw body. Whole pages only, same reasoning
// lib/copilot/projectStories.js gives: a page trimmed mid-sentence reads as
// a claim that stops partway through.
function formatPageBlock(page) {
  const title = str(page.title).trim() || "Untitled page";
  const body = str(page.body).trim();
  // formatAttachment stays the ONLY thing that turns an attachment row into
  // a line — it is the enforcement point for "name/kind/notes/transcript and
  // nothing else", so a raw row's storage_path or signed url can never reach
  // a prompt no matter what shape the caller fetched.
  const all = (Array.isArray(page.attachments) ? page.attachments : []).map(formatAttachment).filter(Boolean);
  const attachmentLines = all.slice(0, MAX_LISTED_ATTACHMENTS);
  const droppedAttachmentCount = all.length - attachmentLines.length;

  const parts = [`## ${title} (page id: ${page.id})`];
  if (attachmentLines.length > 0) parts.push(`Attachments:\n${attachmentLines.join("\n")}`);
  if (body) parts.push(body);

  return {
    text: parts.join("\n\n"),
    hasAttachments: attachmentLines.length > 0,
    droppedAttachmentCount,
  };
}

// buildMeetingContext({ pages, topic, transcript, pinnedPageId }) ->
// { content, includedPageIds, droppedPageCount, truncated }.
//
// Ranking: `pinnedPageId` (the page open when the meeting started — the one
// relevance signal that is not a guess) always sorts first; everything else
// by term overlap against `topic + transcript`, ties kept in `position`
// order.
//
// Packing: whole pages only, and this STOPS at the first page that doesn't
// fit rather than skipping it. This list IS relevance-ranked, so
// skip-and-continue would silently promote a less relevant short page over a
// more relevant long one, and neither the model nor the user could tell it
// happened.
//
// The interview copilot's own packer, lib/experience/knowledgeBase.js's
// buildKnowledgeBaseBlock, AGREES with this — it stops for exactly the same
// reason on exactly the same kind of list. (This comment used to frame the
// rule as a contrast with lib/copilot/projectStories.js's
// buildProjectStoriesBlock, "which skips a page that doesn't fit". That
// function is deleted, its successor stops too, and the contrast now teaches
// the next reader the opposite of the truth. The one place skip-and-continue
// survives is BLOCK-level packing inside a single page's excerpt —
// knowledgeBase.js's excerptForQuery — where the gaps are already marked and
// the list is not itself the ranking.)
//
// Runs on every ~20-second read of a live meeting, so it may never throw —
// every input is treated as possibly missing, empty, or full of junk.
export function buildMeetingContext(input) {
  const src = input && typeof input === "object" ? input : {};
  const pageList = Array.isArray(src.pages) ? src.pages : [];
  const eligible = pageList.filter(isEligibleMeetingPage);

  const pinnedPageId = typeof src.pinnedPageId === "string" ? src.pinnedPageId : null;
  const pinned = pinnedPageId ? eligible.find((page) => page.id === pinnedPageId) || null : null;

  // Speaker labels are stripped from the RANKING query only — see
  // stripSpeakerLabels. The transcript the model is shown keeps its labels
  // (who said what is real information to a reader); it is only the term
  // counting that must not treat "Others" as a subject of conversation.
  const queryText = `${str(src.topic)} ${stripSpeakerLabels(src.transcript)}`;
  const restCandidates = pinned ? eligible.filter((page) => page.id !== pinned.id) : eligible;
  const ranked = rankMeetingPages(restCandidates, queryText);
  const ordered = pinned ? [pinned, ...ranked] : ranked;

  const budgetForPages = Math.max(0, MAX_MEETING_CONTEXT_CHARS - NOTICE_RESERVE_CHARS);

  const included = [];
  let used = 0;
  for (const page of ordered) {
    const block = formatPageBlock(page);
    const addLen = block.text.length + (included.length > 0 ? SEPARATOR.length : 0);
    // Stop, don't skip — see this function's own comment above on why a
    // relevance-ranked list cannot skip-and-continue, and on
    // lib/experience/knowledgeBase.js agreeing.
    if (used + addLen > budgetForPages) break;
    included.push({ id: page.id, ...block });
    used += addLen;
  }

  const includedPageIds = included.map((entry) => entry.id);
  const droppedPageCount = ordered.length - included.length;
  const anyAttachmentsShown = included.some((entry) => entry.hasAttachments);

  const notices = [];
  // Present whenever an attachment is listed AT ALL in what's actually
  // included this read — never conditioned on WHICH kind of attachment it
  // is, and never omitted just because every attachment present happens to
  // be one pageContext.js would have disclaimed anyway (that would make the
  // notice correct only by accident and let it silently vanish the moment a
  // read holds only decks). See this file's header comment for the failure
  // this exists to prevent.
  if (anyAttachmentsShown) notices.push(NO_ATTACHMENT_BYTES_NOTICE);
  // Same principle one level down: an inventory silently cut at
  // MAX_LISTED_ATTACHMENTS is a model reading a partial file list and
  // believing it complete. Worded "not listed" rather than "not included" so
  // it cannot be confused with the dropped-PAGE sentence below.
  const droppedAttachmentCount = included.reduce((total, entry) => total + entry.droppedAttachmentCount, 0);
  if (droppedAttachmentCount > 0) {
    notices.push(`${pluralize(droppedAttachmentCount, "attachment")} not listed to fit the meeting context budget.`);
  }
  if (droppedPageCount > 0) {
    notices.push(`${pluralize(droppedPageCount, "page")} not included to fit the meeting context budget.`);
  }

  const body = included.map((entry) => entry.text).join(SEPARATOR);
  const noticeBlock = notices.length > 0 ? `[Note: ${notices.join(" ")}]` : "";
  let content = [body, noticeBlock].filter(Boolean).join("\n\n");
  if (!content) content = "No pages from the knowledge base were available for this meeting.";

  // Defensive final clamp, mirroring pageContext.js's own: the budgeting
  // above is designed to always hold, but the hard contract (content never
  // exceeds MAX_MEETING_CONTEXT_CHARS) must still hold even if some future
  // change ever overshoots it. Included page blocks always precede the
  // notices in `content`, so a tail cut here can only ever remove notice
  // text, never a page already promised to be whole.
  if (content.length > MAX_MEETING_CONTEXT_CHARS) {
    content = content.slice(0, MAX_MEETING_CONTEXT_CHARS);
  }

  return {
    content,
    includedPageIds,
    droppedPageCount,
    truncated: droppedPageCount > 0,
  };
}
