"use client";

import { useId, useState } from "react";
import Box from "@mui/material/Box";
import Button from "@mui/material/Button";
import Stack from "@mui/material/Stack";
import Typography from "@mui/material/Typography";
import CheckCircleOutlined from "@mui/icons-material/CheckCircleOutlined";
import PlaylistRemove from "@mui/icons-material/PlaylistRemove";
import ReportProblemOutlined from "@mui/icons-material/ReportProblemOutlined";
import MarkdownPreview from "./MarkdownPreview.js";
import KnowledgeQuestionBox from "./KnowledgeQuestionBox.js";
import KnowledgeHistory from "./KnowledgeHistory.js";
import { useKnowledgeScope } from "../../hooks/useKnowledgeScope";
import {
  ANNOUNCE_TOGGLE,
  BODY_SX,
  BTN_SX,
  CAPTION_SX,
  FAILED_SX,
  HEADING_SX,
  HIDDEN_STATUS_SX,
  LEAD_IN_SX,
  OK_LINE_SX,
  PANEL_SX,
  PROSE_SX,
  SCOPE_SX,
  SENTENCE_SX,
  SEP_SX,
  STATE_ROW_SX,
  SUBHEAD_SX,
  renderInertLink,
} from "./knowledgePanelStyles.js";

// One panel, mounted once, covering one scope: the root of the knowledge base
// or one page and everything beneath it. It renders a stored summary and the
// disclosures that make that summary honest, and it hosts the grounded
// question box beneath them.
//
// ------------------------------------------------------------------------
// THE HEADING DOES NOT OVERCLAIM. "Ask this knowledge base" is FALSE on a page
// scope — the panel covers one branch of the tree, not the whole base — and a
// feature whose entire premise is "a summary that silently omits half its
// scope while presenting itself as complete is worse than no summary" cannot
// overclaim in its own heading. So the heading is short and fixed, and the
// scope claim is a separate, scope-dependent sentence directly beneath it.
//
// ------------------------------------------------------------------------
// COVERAGE AND FRESHNESS ARE TWO INDEPENDENT AXES, TWO ORDERED LINES, NEVER
// MERGED. A summary that is both stale and partial is the ordinary case for a
// subtree someone has been editing, and one control cannot carry two axes.
//
// EACH LINE SURVIVES MONOCHROME THROUGH THREE CHANNELS, NONE OF THEM COLOUR:
//   * the GLYPH SILHOUETTE — a closed ring, a closed triangle, open bars;
//   * the WEIGHT — the two attention states open with a bold lead-in, the
//     complete state has no run at weight 700 anywhere;
//   * the SENTENCE itself, which states the fact in words.
// The `…Outline` legacy icon aliases do not exist in this icon package's
// version, so the three imported above are the verified names.
//
// There is no tinted band behind any of it. A soft band measures 1.01–1.34:1
// at its own edge — a colour claim with no outline to carry it — and the
// danger token on its own soft ground is 3.98:1 in dark against a 4.5 floor:
// correct in light, non-conformant in dark, from the same two tokens.
//
// ------------------------------------------------------------------------
// ZERO MOTION, AND THAT IS A MEASUREMENT RATHER THAN A PREFERENCE.
// `prefers-reduced-motion` occurs zero times in this repo and zero times in
// the installed MUI tree, so there is no shared guard to opt into: any motion
// added here WILL play for a user who asked for none. The body's collapse is
// therefore a bare ternary, which also actually removes the subtree — MUI's
// own collapsing container leaves it mounted and readable while computing
// `visibility: hidden`, which would silence a live region placed inside it.
//
// The live region and the log button both live OUTSIDE the collapsible body.
// A log button behind a collapse is not "always visible, never behind a menu",
// and it must render in every state including a failure and a zero-out —
// those are the two states it exists for.

const OMITTED_PAGE_SIZE = 10;
// Roughly ten line boxes at MarkdownPreview's own 14px / 1.7. Below this the
// body cannot reach the collapsed cap, so offering to expand it would be a
// control that does nothing.
const OVERFLOW_HINT_CHARS = 600;

// AC-3.7's closed reason vocabulary, in the user's words rather than the
// pipeline's. "unknown" is a real arm, not a fallback nobody meant: a stored
// row written by an older shape has a reason this list does not carry, and
// saying so is more honest than picking the nearest phrase.
const REASON_PHRASE = {
  budget: "did not fit the character budget",
  ineligible: "is archived or was generated by another feature",
  "eligibility-threw": "could not be checked",
  "no-material": "has nothing written in it",
  "no-id": "could not be identified",
  unknown: "was left out for a reason this record does not name",
};

function scopeSentenceFor(scope) {
  if (!scope.pageId) {
    return `Covers all ${scope.pageCount} page${scope.pageCount === 1 ? "" : "s"} in your knowledge base.`;
  }
  const name = scope.title || "this page";
  const children = Math.max(0, scope.pageCount - 1);
  if (children === 0) return `Covers “${name}” only — it has no sub-pages.`;
  return `Covers “${name}” and its ${children} sub-page${children === 1 ? "" : "s"}.`;
}

/**
 * The coverage line: one of eight sentences, chosen in an order that is itself
 * load-bearing.
 *
 * "zero-out" is tested BEFORE the generic partial-coverage arm and before the
 * stored `status`, because a run where input arrived and nothing came out is
 * the state that exposes a wiring bug — the block builder's eligibility rule
 * has no default and falls back to refusing everything, and an empty scope, a
 * forgotten rule and an all-ineligible scope produce a byte-identical result.
 * Rendering it as "there is nothing here" is exactly how that bug ships.
 *
 * "legacy" is tested before the consistency check, because a row that predates
 * this feature has nothing to be consistent WITH: "cannot confirm" and "the
 * record disagrees" are two different facts and get two different sentences.
 */
function coverageLineFor({ view, coverage, scope, generating }) {
  if (view.state === "none") {
    return generating
      ? { icon: null, leadIn: "", sentence: `Writing a summary of ${scope.pageCount} page${scope.pageCount === 1 ? "" : "s"}…` }
      : { icon: null, leadIn: "", sentence: "No summary has been written for this scope yet." };
  }

  if (view.state === "legacy") {
    return {
      icon: ReportProblemOutlined,
      leadIn: "Coverage unknown —",
      sentence:
        "this summary was saved before the panel recorded which pages it covered, so its coverage and freshness cannot be confirmed.",
    };
  }

  if (view.state === "zero-out") {
    const inScope = view.counts && Number.isInteger(view.counts.pagesInScope) ? view.counts.pagesInScope : 0;
    const stage = view.anomalyStage || "an unrecorded stage";
    return {
      icon: ReportProblemOutlined,
      leadIn: "Nothing reached the model —",
      sentence: `${inScope} page${inScope === 1 ? " is" : "s are"} in this scope and none of them reached the model. The count went to zero at “${stage}”. Nothing below describes them; download the log for the full breakdown.`,
    };
  }

  if (view.state === "empty-scope") {
    return {
      icon: CheckCircleOutlined,
      leadIn: "",
      sentence: scope.pageId
        ? `“${scope.title || "This page"}” has no sub-pages and nothing written in it yet, so there is nothing to summarise.`
        : "Your knowledge base has no pages yet, so there is nothing to summarise.",
    };
  }

  if (!coverage.consistent) {
    return {
      icon: ReportProblemOutlined,
      leadIn: "Record mismatch —",
      sentence:
        "the stored record does not match this summary, so its coverage and freshness cannot be confirmed. The summary itself is shown below unchanged.",
    };
  }

  if (coverage.excluded === 0) {
    return {
      icon: CheckCircleOutlined,
      leadIn: "",
      sentence: `All ${coverage.total} page${coverage.total === 1 ? "" : "s"} in this scope are in this summary.`,
    };
  }

  return {
    icon: PlaylistRemove,
    leadIn: "Not everything is in —",
    sentence: `${coverage.included} of ${coverage.total} pages in this scope are in this summary. ${coverage.excluded} ${
      coverage.excluded === 1 ? "was" : "were"
    } left out.`,
  };
}

// "changed", never "edited": a drag stamps `updated_at` on up to a whole
// sibling list, so a reorder would read as an edit. The neutral word is the
// honest one, and moves get their own clause so the two are not conflated.
function freshnessSentences(staleness) {
  const out = [];
  const say = (list, singular, plural) => {
    if (list.length === 0) return;
    out.push(`${list.length} ${list.length === 1 ? singular : plural}`);
  };
  say(staleness.added, "page has been added to this scope", "pages have been added to this scope");
  say(staleness.removed, "page this summary covered has been deleted", "pages this summary covered have been deleted");
  say(staleness.moved, "page has moved", "pages have moved");
  say(staleness.changed, "page has changed", "pages have changed");
  return out;
}

function StateLine({ icon: Icon, leadIn, sentence, testAttr }) {
  const attrs = testAttr ? { [testAttr]: "" } : {};
  return (
    <Box sx={STATE_ROW_SX} {...attrs}>
      {Icon ? <Icon sx={{ fontSize: 16, mt: "1px", color: leadIn ? "var(--warning)" : "var(--text-secondary)" }} /> : null}
      <Typography component="span" sx={leadIn ? SENTENCE_SX : OK_LINE_SX}>
        {leadIn ? (
          <Typography component="span" data-kb-lead-in sx={LEAD_IN_SX}>
            {`${leadIn} `}
          </Typography>
        ) : null}
        {sentence}
      </Typography>
    </Box>
  );
}

export default function KnowledgePanel({ scopePageId, pages, loading, signedOut, error, onSelectPage }) {
  const headingId = useId();
  const kb = useKnowledgeScope({ scopePageId, pages, loading, signedOut, error });
  const [confirmingRegenerate, setConfirmingRegenerate] = useState(false);
  const [showAllOmitted, setShowAllOmitted] = useState(false);

  // Signed out renders NOTHING — the tab already carries its own signed-out
  // notice, and a second one underneath saying the same thing is noise. Every
  // hook above still ran unconditionally; this is the only place execution
  // stops.
  if (signedOut) return null;

  const { view, coverage, staleness, scope, busy, announcement } = kb;
  const line = coverageLineFor({ view, coverage, scope, generating: busy.generating });
  // The freshness signal is refused whenever the coverage claim is: a stored
  // record that cannot be trusted about which pages it covered cannot be
  // trusted about whether they have changed either.
  const fresh = coverage.consistent && view.state !== "legacy" ? freshnessSentences(staleness) : [];
  const omitted = Array.isArray(view.omitted) ? view.omitted : [];
  const shownOmitted = showAllOmitted ? omitted : omitted.slice(0, OMITTED_PAGE_SIZE);

  function selectCitedPage(pageId) {
    // Activating a citation changes the tree selection, which changes this
    // panel's own scope in the same frame — the summary, the coverage line,
    // the history and the draft all swap out at once. It is the single most
    // surprising thing this panel can do, so it is announced as real text
    // rather than explained by an aria-label the sighted user never sees.
    const target = (Array.isArray(pages) ? pages : []).find((p) => p && p.id === pageId);
    kb.announce(`Opened “${(target && target.title) || "that page"}”. This panel now covers it.`);
    if (onSelectPage) onSelectPage(pageId);
  }

  function requestRegenerate() {
    if (busy.generating) return;
    setConfirmingRegenerate(true);
  }

  return (
    <Box role="region" aria-labelledby={headingId} sx={PANEL_SX}>
      <Stack direction="row" sx={{ alignItems: "center", justifyContent: "space-between", gap: 1, flexWrap: "wrap" }}>
        <Typography id={headingId} component="h3" sx={HEADING_SX}>
          Ask these pages
        </Typography>
        <Stack direction="row" sx={{ gap: 1, flexWrap: "wrap" }}>
          <Button size="small" onClick={() => kb.setOpen(!kb.open)} aria-expanded={!!kb.open} sx={BTN_SX}>
            {kb.open ? "Hide this panel" : "Show this panel"}
          </Button>
          {/* Always visible, always enabled, never behind the collapse and
              never behind a menu — including in the two states with nothing
              else to show. */}
          <Button size="small" onClick={kb.downloadLog} sx={BTN_SX}>
            Download log
          </Button>
        </Stack>
      </Stack>

      <Typography data-kb-scope sx={SCOPE_SX}>
        {scopeSentenceFor(scope)}
      </Typography>

      {error ? (
        // A FAILED PAGE LOAD IS NOT AN EMPTY KNOWLEDGE BASE. `pages`
        // initialises to [] and a failed fetch leaves it [] with loading
        // false, so without this arm a failure renders as a base with nothing
        // in it — and that state does not call the model, so the failure would
        // be completely silent.
        <Typography sx={{ ...FAILED_SX, mt: 0.5 }}>
          Your pages could not be loaded, so this panel cannot describe them.
        </Typography>
      ) : kb.loadError ? (
        <Typography sx={{ ...FAILED_SX, mt: 0.5 }}>{kb.loadError}</Typography>
      ) : (
        <StateLine icon={line.icon} leadIn={line.leadIn} sentence={line.sentence} testAttr="data-kb-coverage" />
      )}

      {fresh.length > 0 ? (
        <StateLine
          icon={ReportProblemOutlined}
          leadIn="Out of date —"
          sentence={`${fresh.join("; ")} since this summary was written. Attachments are not covered by this check at all.`}
          testAttr="data-kb-freshness"
        />
      ) : null}

      {view.truncatedRead ? (
        <Typography sx={{ ...CAPTION_SX, mt: 0.5 }}>
          Your pages came back as a partial list, so not every page could be read into this summary.
        </Typography>
      ) : null}

      {view.residueRemoved > 0 ? (
        <Typography sx={{ ...CAPTION_SX, mt: 0.5 }}>
          {`${view.residueRemoved} link${view.residueRemoved === 1 ? " was" : "s were"} removed from this summary before it was saved, including any address you had written yourself.`}
        </Typography>
      ) : null}

      {view.state === "failed" && view.error ? (
        <Typography sx={{ ...FAILED_SX, mt: 0.5 }}>
          {view.summaryText
            ? `The last attempt to rewrite this summary failed: ${view.error} What you see below is the previous one.`
            : `The summary could not be written: ${view.error}`}
        </Typography>
      ) : null}

      {kb.open ? (
        <Box sx={{ mt: 1 }}>
          {view.summaryText ? (
            <>
              <Box sx={{ ...BODY_SX(kb.bodyExpanded), ...PROSE_SX }}>
                <MarkdownPreview markdown={view.summaryText} renderLink={renderInertLink} />
              </Box>
              {view.summaryText.length > OVERFLOW_HINT_CHARS ? (
                <Button size="small" onClick={() => kb.setBodyExpanded(!kb.bodyExpanded)} sx={{ ...BTN_SX, mt: 0.5 }}>
                  {kb.bodyExpanded ? "Show less of the summary" : "Show the whole summary"}
                </Button>
              ) : null}
            </>
          ) : null}

          {omitted.length > 0 ? (
            <Box sx={{ mt: 1 }}>
              {/* NAMED, NEVER COUNTED. "3 pages were left out" is the notice
                  the owner has already asked "which ones?" of, and answering
                  that is this feature's core value. */}
              <Typography component="h4" sx={SUBHEAD_SX}>
                Left out of this summary
              </Typography>
              {shownOmitted.map((entry) => (
                <Typography key={entry.id} data-kb-omitted-row sx={CAPTION_SX}>
                  {`${entry.title || "An untitled page"} — ${REASON_PHRASE[entry.reason] || REASON_PHRASE.unknown}`}
                </Typography>
              ))}
              {!showAllOmitted && omitted.length > OMITTED_PAGE_SIZE ? (
                <Button size="small" onClick={() => setShowAllOmitted(true)} sx={{ ...BTN_SX, mt: 0.5 }}>
                  {`Show all ${omitted.length}`}
                </Button>
              ) : null}
              {coverage.attachmentsSkipped > 0 ? (
                <Typography sx={{ ...CAPTION_SX, mt: 0.5 }}>
                  {`${coverage.attachmentsSkipped} attachment${coverage.attachmentsSkipped === 1 ? " was" : "s were"} not listed.`}
                </Typography>
              ) : null}
            </Box>
          ) : null}

          <KnowledgeQuestionBox
            pagesInScope={scope.pageCount}
            pages={pages}
            draft={kb.draft}
            onDraftChange={kb.setDraft}
            onAsk={kb.ask}
            busy={busy.asking}
            askError={kb.askError}
            answer={kb.lastAnswer}
            onSelectPage={selectCitedPage}
          />

          <KnowledgeHistory
            questions={kb.questions}
            hasMore={kb.hasMore}
            pages={pages}
            open={kb.historyOpen}
            onToggleOpen={kb.setHistoryOpen}
            onSelectPage={selectCitedPage}
            onDelete={kb.removeQuestion}
            pendingDelete={kb.pendingDelete}
            onUndoDelete={kb.undoDelete}
            onClearAll={kb.clearQuestions}
          />

          <Box sx={SEP_SX}>
            {confirmingRegenerate ? (
              // Inline and in place, never a nested dialog. `autoFocus` sits
              // on the NON-destructive button: the user arrived here by
              // pressing the trigger with Enter, and a second Enter on a
              // focused destructive button would replace the summary before
              // they had read a word.
              <Stack sx={{ gap: 0.5, alignItems: "flex-start" }}>
                <Typography sx={{ ...SENTENCE_SX, fontSize: 12.5 }}>
                  Rewrite this summary? The current one is replaced and there is no earlier version to go back to.
                </Typography>
                <Stack direction="row" sx={{ gap: 1 }}>
                  <Button autoFocus size="small" onClick={() => setConfirmingRegenerate(false)} sx={BTN_SX}>
                    Keep what I have
                  </Button>
                  <Button
                    variant="outlined"
                    size="small"
                    onClick={() => {
                      setConfirmingRegenerate(false);
                      kb.generate();
                    }}
                    sx={BTN_SX}
                  >
                    Rewrite it
                  </Button>
                </Stack>
              </Stack>
            ) : (
              <Button
                variant="outlined"
                size="small"
                aria-disabled={busy.generating ? "true" : undefined}
                onClick={requestRegenerate}
                sx={BTN_SX}
              >
                {busy.generating ? "Generating…" : "Regenerate summary"}
              </Button>
            )}
          </Box>
        </Box>
      ) : null}

      {/* Always mounted, outside the collapsible body, and its text is the
          only thing that changes. The auto-generated summary is the one event
          in this panel with no sighted-user surface of its own, so it is the
          one that would otherwise go unannounced. */}
      <Box component="span" role="status" aria-live="polite" sx={HIDDEN_STATUS_SX}>
        {announcement.text}
        {announcement.seq % 2 === 1 ? ANNOUNCE_TOGGLE : ""}
      </Box>
    </Box>
  );
}
