// Node environment (the repo default) on purpose: everything asserted here is
// a pure function of a Response-shaped object and a few numbers. No DOM.
//
// This file is the one that actually closes the reported bug:
//
//     Unexpected token 'R', "Request En"... is not valid JSON
//
// `lib/chat/chatbot.js:266` calls `await response.json()` UNCONDITIONALLY,
// [HISTORICAL LINE REFERENCE -- DO NOT REPOINT. This cites the file as it
// stood BEFORE the fix, as the record of what the fix was for. The line no
// longer holds that code; repointing it at whatever moved in would erase the
// record. The same applies to `:267` further down.]
// before the `response.ok` check on the next line. When Vercel rejects the
// POST at the edge with its 4.5 MB App Router body cap, the body is the plain
// string "Request Entity Too Large" and `.json()` throws that SyntaxError,
// which then lands in `setChatError` as the message the user reads.
//
// Two properties are non-negotiable and are asserted structurally rather than
// by prose match:
//
//   1. `response.json` is NEVER called on this path -- the spies here have
//      zero calls in every fixture, including the 200/JSON happy path.
//   2. The body is read EXACTLY ONCE, via `response.text()`. A second read of
//      a real `Response` throws "body stream already read", so "exactly once"
//      is a correctness property, not a style preference.
//
// The content-type fixtures are the load-bearing part. A platform 413 is NOT
// generated by `app/api/chat/route.js` -- it never runs -- so nothing
// guarantees a content-type at all. An implementation that branches on
// `content-type` instead of `status` silently falls through to `.json()` for
// at least one of these four fixtures and reproduces the exact reported
// error. The `headers: { get: () => null }` fixture is the one that catches
// it.
//
// Prior art followed: lib/llm/engines/externalEngine.js:57-66 (attempt JSON,
// fall back on parse failure; see its comment at :28-29 -- "413 returns an
// HTML page (not JSON), so it's handled separately").

// NOTE: there are deliberately NO source-text assertions in this file (no
// grep for `5 * 1024 * 1024`, for "max 5 MB", or for `response.json(`). They
// would fail a behaviourally CORRECT implementation, because this repo's
// convention is to explain a change in a comment right where it lands -- "the
// old gate was `5 * 1024 * 1024`" and "we deliberately never call
// `response.json()` here" are exactly the comments a good fix would carry, and
// a grep cannot tell a comment from a call. They also buy nothing: renaming
// the variable to `res` slips past the grep while the behavioural spies below
// still catch it. Both properties are pinned behaviourally instead -- by the
// twelve `expect(res.json).toHaveBeenCalledTimes(0)` assertions here, and by
// "refuses a file over the derived cap" / "applies the same per-file cap to
// text attachments" in chatbot.attachments.test.js.

import { describe, it, expect, vi } from "vitest";
// Namespace import, deliberately: these symbols do not exist yet. A named
// import of a missing export can fail at module-link time, which would make
// this file fail for the WRONG reason (a broken import, not absent
// behaviour). Through the namespace, a missing export is plainly `undefined`.
import * as chatbot from "./chatbot.js";

// A Response-shaped double. `json` is a spy that THROWS the way a real
// `Response.json()` throws on a non-JSON body, so an implementation that
// still calls it fails loudly rather than quietly returning undefined.
function fakeResponse({ status, body, contentType }) {
  const res = {
    ok: status >= 200 && status < 300,
    status,
    headers: { get: () => (contentType === undefined ? null : contentType) },
    text: vi.fn(async () => body),
    json: vi.fn(async () => {
      throw new SyntaxError(
        `Unexpected token '${String(body).charAt(0)}', "${String(body).slice(0, 10)}"... is not valid JSON`,
      );
    }),
  };
  return res;
}

// A 200 whose body really is JSON: `json` would succeed here, so it stays a
// spy but resolves. It must STILL never be called.
function fakeJsonResponse({ status, payload }) {
  const body = JSON.stringify(payload);
  return {
    ok: status >= 200 && status < 300,
    status,
    headers: { get: () => "application/json" },
    text: vi.fn(async () => body),
    json: vi.fn(async () => JSON.parse(body)),
  };
}

// The four shapes a platform-generated 413 can arrive in. Vercel's edge
// rejection is not the app's own JSON error response, so the content-type is
// whatever the platform felt like sending -- including nothing at all.
const BODY_413 = "Request Entity Too Large";
const CONTENT_TYPES_413 = [
  ["no content-type header at all", undefined],
  ["text/plain", "text/plain; charset=utf-8"],
  ["text/html", "text/html; charset=utf-8"],
  ["application/octet-stream", "application/octet-stream"],
];

describe("readChatResponse: the 413 that produced the reported error", () => {
  for (const [label, contentType] of CONTENT_TYPES_413) {
    it(`classifies a 413 by status, not content-type (${label})`, async () => {
      const res = fakeResponse({ status: 413, body: BODY_413, contentType });

      const result = await chatbot.readChatResponse(res);

      // (a) The body is read exactly once, and only as text.
      expect(res.json).toHaveBeenCalledTimes(0);
      expect(res.text).toHaveBeenCalledTimes(1);

      // (b) The failure is reported, not thrown.
      expect(result.ok).toBe(false);

      // (c) ABSENCE: the reported error string never reaches the user.
      expect(result.error).not.toMatch(/is not valid JSON/i);
      expect(result.error).not.toMatch(/Unexpected token/i);
      expect(result.error).not.toMatch(/\bJSON\b/);
      // The raw platform body is engineer-speak; it is not an answer either.
      expect(result.error).not.toBe(BODY_413);

      // (d) PAIRED POSITIVE CONTROL for (c): it says what happened, states
      // the limit, and names the remedy a job-seeker can actually perform.
      expect(result.error).toMatch(/too (big|large)/i);
      expect(result.error).toMatch(/4\.5\s*MB/i);
      expect(result.error).toMatch(/(remove|detach|fewer|smaller)/i);
      expect(result.error).toMatch(/(file|attach)/i);
    });
  }

  it("PAIRED POSITIVE CONTROL: a 200 JSON reply still parses, and still never calls .json()", async () => {
    const res = fakeJsonResponse({ status: 200, payload: { reply: "Here is how I'd reframe that bullet." } });

    const result = await chatbot.readChatResponse(res);

    expect(res.json).toHaveBeenCalledTimes(0);
    expect(res.text).toHaveBeenCalledTimes(1);
    expect(result.ok).toBe(true);
    expect(result.reply).toBe("Here is how I'd reframe that bullet.");
  });
});

describe("readChatResponse: B1 -- a 500's own JSON error must NOT reach the user verbatim", () => {
  // app/api/chat/route.js:258 is a catch-all: `Response.json({ error:
  // err?.message || "Chat request failed." }, { status: 500 })`. A bad Gemini
  // key, an SDK exception, or a Supabase failure all funnel through THIS one
  // line, so `err.message` can be raw engineer-speak like
  // "[GoogleGenerativeAI Error]: API key not valid. Please pass a valid API
  // key." -- exactly the class of leak this whole change exists to close,
  // just arriving through the 500 door instead of the SyntaxError door.
  it("a 500 with a real {error} JSON body still renders the generic message, not the raw text", async () => {
    const res = fakeJsonResponse({
      status: 500,
      payload: { error: "[GoogleGenerativeAI Error]: API key not valid. Please pass a valid API key." },
    });

    const result = await chatbot.readChatResponse(res);

    expect(res.json).toHaveBeenCalledTimes(0);
    expect(res.text).toHaveBeenCalledTimes(1);
    expect(result.ok).toBe(false);
    // ABSENCE: the raw provider/SDK error string never reaches the user.
    expect(result.error).not.toContain("fetch failed");
    expect(result.error).not.toMatch(/GoogleGenerativeAI/);
    expect(result.error).not.toMatch(/API key/);
    // PAIRED POSITIVE CONTROL: the generic "couldn't reach" fallback instead.
    expect(result.error).toMatch(/(couldn't reach|could not reach|unavailable)/i);
  });

  it("status 500 with {\"error\":\"fetch failed\"} renders the generic message and does NOT contain 'fetch failed'", async () => {
    const res = fakeJsonResponse({ status: 500, payload: { error: "fetch failed" } });

    const result = await chatbot.readChatResponse(res);

    expect(result.ok).toBe(false);
    expect(result.error).not.toContain("fetch failed");
    expect(result.error).toMatch(/(couldn't reach|could not reach|unavailable)/i);
  });

  it("PAIRED POSITIVE CONTROL: 400 and 502 route errors still pass through a 500 does not", async () => {
    // Same shape of response (a real {error} JSON body, non-2xx) but at the
    // two statuses that must remain verbatim -- proves the gate keys on
    // status 500 specifically, not on "has a parsed error string".
    const res400 = fakeJsonResponse({ status: 400, payload: { error: "No messages provided." } });
    const res502 = fakeJsonResponse({ status: 502, payload: { error: "Could not generate a reply." } });

    expect((await chatbot.readChatResponse(res400)).error).toBe("No messages provided.");
    expect((await chatbot.readChatResponse(res502)).error).toBe("Could not generate a reply.");
  });
});

describe("readChatResponse: the other transport failure modes", () => {
  it("a 5xx HTML error page says it could not reach the assistant, and to retry", async () => {
    const res = fakeResponse({
      status: 500,
      body: "<!DOCTYPE html><html><body><h1>500: INTERNAL_SERVER_ERROR</h1></body></html>",
      contentType: "text/html; charset=utf-8",
    });

    const result = await chatbot.readChatResponse(res);

    expect(res.json).toHaveBeenCalledTimes(0);
    expect(res.text).toHaveBeenCalledTimes(1);
    expect(result.ok).toBe(false);
    expect(result.error).not.toMatch(/is not valid JSON/i);
    // No raw markup in a message a non-technical user reads.
    expect(result.error).not.toMatch(/<[a-z!]/i);
    expect(result.error).toMatch(/(couldn't reach|could not reach|unavailable)/i);
    expect(result.error).toMatch(/(try again|again in a moment|retry)/i);
  });

  it("a 504 says it took too long", async () => {
    const res = fakeResponse({
      status: 504,
      body: "An error occurred with your deployment\n\nFUNCTION_INVOCATION_TIMEOUT",
      contentType: "text/plain; charset=utf-8",
    });

    const result = await chatbot.readChatResponse(res);

    expect(res.json).toHaveBeenCalledTimes(0);
    expect(res.text).toHaveBeenCalledTimes(1);
    expect(result.ok).toBe(false);
    expect(result.error).not.toMatch(/is not valid JSON/i);
    expect(result.error).toMatch(/(took too long|timed out|taking too long)/i);
  });

  it("an empty 200 body says the reply did not come through", async () => {
    const res = fakeResponse({ status: 200, body: "", contentType: "application/json" });

    const result = await chatbot.readChatResponse(res);

    expect(res.json).toHaveBeenCalledTimes(0);
    expect(res.text).toHaveBeenCalledTimes(1);
    expect(result.ok).toBe(false);
    expect(result.error).not.toMatch(/is not valid JSON/i);
    expect(result.error).toMatch(/(empty|incomplete|truncated|didn't come|did not come|nothing came)/i);
  });

  it("a truncated 200 body says the reply did not come through", async () => {
    const res = fakeResponse({
      status: 200,
      body: '{"reply":"Here is how I',
      contentType: "application/json",
    });

    const result = await chatbot.readChatResponse(res);

    expect(res.json).toHaveBeenCalledTimes(0);
    expect(res.text).toHaveBeenCalledTimes(1);
    expect(result.ok).toBe(false);
    expect(result.error).not.toMatch(/is not valid JSON/i);
    expect(result.error).toMatch(/(empty|incomplete|truncated|didn't come|did not come|nothing came)/i);
  });
});

describe("readChatResponse: the route's own JSON errors still surface verbatim", () => {
  // These three strings are every `{ error }` app/api/chat/route.js returns.
  // This is the one path that works TODAY (a JSON body parses, and :267 reads
  // `payload.error`); the fix must not swallow it.
  const ROUTE_ERRORS = [
    [400, "No messages provided."],
    [502, "Could not generate a reply."],
    [502, "Empty response from Gemini."],
  ];

  for (const [status, message] of ROUTE_ERRORS) {
    it(`passes through the route's ${status} "${message}" unchanged`, async () => {
      const res = fakeJsonResponse({ status, payload: { error: message } });

      const result = await chatbot.readChatResponse(res);

      expect(res.json).toHaveBeenCalledTimes(0);
      expect(res.text).toHaveBeenCalledTimes(1);
      expect(result.ok).toBe(false);
      expect(result.error).toBe(message);
    });
  }
});

describe("attachment budget: the arithmetic, stated", () => {
  // MAX_REQUEST_BYTES = 4_500_000   Vercel's App Router body cap, read
  //                                 decimally (4.5 MiB = 4_718_592 would be
  //                                 the optimistic reading; decimal is the
  //                                 conservative one). Not configurable.
  // CHAT_BODY_OVERHEAD_BYTES = 500_000  reserved for everything else in the
  //                                 body: the transcript, resumeText, the
  //                                 applications array, pinnedContext, and
  //                                 the JSON scaffolding.
  // MAX_ATTACHMENT_PAYLOAD_BYTES = 4_500_000 - 500_000 = 4_000_000
  //                                 base64 characters, across ALL attachments.
  // MAX_BINARY_ATTACHMENT_BYTES:    largest single file whose base64 fits.
  //                                 4 * ceil(n/3) <= 4_000_000
  //                              => ceil(n/3) <= 1_000_000
  //                              => n <= 3_000_000 decoded bytes.

  it("base64Length uses the CEILING formula, not n * 4/3", () => {
    expect(chatbot.base64Length(0)).toBe(0);
    expect(chatbot.base64Length(1)).toBe(4);
    expect(chatbot.base64Length(2)).toBe(4);
    expect(chatbot.base64Length(3)).toBe(4);
    expect(chatbot.base64Length(4)).toBe(8);
    expect(chatbot.base64Length(5)).toBe(8);
    expect(chatbot.base64Length(6)).toBe(8);
    // The naive n * 4/3 gives 1.33 and 5.33 here. Both are wrong, and the
    // error is always an UNDER-count, which is what leaves a live failure
    // band right at the top of the range.
    expect(chatbot.base64Length(1)).toBeGreaterThan((1 * 4) / 3);
    expect(chatbot.base64Length(4)).toBeGreaterThan((4 * 4) / 3);
    // Realistic sizes used by the aggregate tests.
    expect(chatbot.base64Length(1_400_000)).toBe(1_866_668);
    expect(chatbot.base64Length(3_000_000)).toBe(4_000_000);
  });

  it("the constants are internally consistent", () => {
    expect(chatbot.MAX_REQUEST_BYTES).toBe(4_500_000);
    expect(chatbot.CHAT_BODY_OVERHEAD_BYTES).toBe(500_000);
    expect(chatbot.MAX_ATTACHMENT_PAYLOAD_BYTES).toBe(
      chatbot.MAX_REQUEST_BYTES - chatbot.CHAT_BODY_OVERHEAD_BYTES,
    );
    expect(chatbot.MAX_ATTACHMENT_PAYLOAD_BYTES).toBe(4_000_000);
  });

  it("M1: the .docx source ceiling is a real, separate limit", () => {
    expect(chatbot.MAX_DOCX_SOURCE_BYTES).toBe(25 * 1024 * 1024);
    expect(chatbot.MAX_DOCX_SOURCE_LABEL).toBe("25 MB");
    // It sits well above the payload cap -- it is a ceiling on the SOURCE
    // (compressed) file, not a restatement of the extracted-content budget.
    expect(chatbot.MAX_DOCX_SOURCE_BYTES).toBeGreaterThan(chatbot.MAX_ATTACHMENT_PAYLOAD_BYTES);
  });

  it("the per-file cap is exactly the largest file whose base64 fits the payload budget", () => {
    expect(chatbot.MAX_BINARY_ATTACHMENT_BYTES).toBe(3_000_000);
    expect(chatbot.base64Length(chatbot.MAX_BINARY_ATTACHMENT_BYTES)).toBe(
      chatbot.MAX_ATTACHMENT_PAYLOAD_BYTES,
    );
    // One byte more does not fit -- the cap is the true maximum, not a
    // round number that happens to be under it.
    expect(chatbot.base64Length(chatbot.MAX_BINARY_ATTACHMENT_BYTES + 1)).toBeGreaterThan(
      chatbot.MAX_ATTACHMENT_PAYLOAD_BYTES,
    );
  });

  it("the old 5 MiB gate sat ABOVE the transport limit, and the new cap sits below it", () => {
    // The bug, in one line: 5 MiB base64-inflates to ~6.99 MB, ~55% over the
    // 4.5 MB the platform will actually carry.
    expect(chatbot.base64Length(5 * 1024 * 1024)).toBeGreaterThan(chatbot.MAX_REQUEST_BYTES);
    expect(chatbot.base64Length(5 * 1024 * 1024)).toBe(6_990_508);
    expect(chatbot.MAX_BINARY_ATTACHMENT_BYTES).toBeLessThan(5 * 1024 * 1024);
  });

  it("the size shown to the user is truthful under BOTH readings of 'MB'", () => {
    const label = chatbot.MAX_ATTACHMENT_SIZE_LABEL;
    expect(typeof label).toBe("string");
    // The spec names this exact string. The band that satisfies the
    // truthfulness properties below is (2.4319, 2.8610] MB, which leaves room
    // for several defensible values; pinning it keeps the refusal copy, the
    // spec, and this file from drifting apart.
    expect(label).toBe("2.8 MB");
    // "5 MB" is a lie for every file between ~3.3 MB and 5 MiB.
    // `(^|\s)` not `\b`: `\b` matches between "." and "5", so `/\b5\s*MB\b/`
    // would reject the perfectly good label "2.5 MB" and report it as saying
    // "5 MB".
    expect(label).not.toMatch(/(^|\s)5\s*MB\b/i);

    const n = Number.parseFloat(label);
    expect(Number.isFinite(n)).toBe(true);
    expect(n).toBeGreaterThan(0);
    // Windows reports file sizes in MiB and labels them "MB"; macOS reports
    // decimal MB. The label must not overstate the cap under EITHER, or a
    // user whose file manager says "3 MB" is told a 3 MB file is fine and
    // then refused.
    expect(n * 1_000_000).toBeLessThanOrEqual(chatbot.MAX_BINARY_ATTACHMENT_BYTES);
    expect(n * 1024 * 1024).toBeLessThanOrEqual(chatbot.MAX_BINARY_ATTACHMENT_BYTES);
    // ...and it must not understate it so far as to be useless.
    expect(n * 1024 * 1024).toBeGreaterThan(chatbot.MAX_BINARY_ATTACHMENT_BYTES * 0.85);
  });

});

// ---------------------------------------------------------------------------
// Chunk A2 -- `readChatResponse` is the SECOND emitter of the refusal
// vocabulary.
//
// The pre-`fetch` gate (the `bodyBytes > MAX_REQUEST_BYTES` throw in
// `runChatRequest`) has the whole body and can measure
// which section is largest. This function does not: a platform 413 arrives
// with nothing but a status, and all it has ever been told is
// `hasAttachments`. A2 closes that gap by letting the caller hand it the
// measurement LAZILY -- a zero-argument function that is only ever invoked on
// the 413 branch, because measuring the five sections costs a second full
// serialization of a body up to 4.5 MB and no successful send should pay it.
//
// The `hasAttachments = true` default and its rationale (the comment directly
// above `readChatResponse`)
// survive untouched: they are what keeps a caller that knows nothing --
// including every existing test in this file -- getting the original wording.
// ---------------------------------------------------------------------------

describe("readChatResponse: AC-53/AC-54 -- the lazily supplied measurement", () => {
  const RES_413 = () =>
    fakeResponse({ status: 413, body: BODY_413, contentType: undefined });

  it("AC-53: a supplied measurement wins, verbatim, and is invoked exactly once", async () => {
    const measure = vi.fn(() => "PRIMARY FROM THE GATE'S OWN MEASUREMENT");
    const res = RES_413();

    const result = await chatbot.readChatResponse(res, {
      hasAttachments: true,
      refusalMessage: measure,
    });

    expect(result).toEqual({ ok: false, error: "PRIMARY FROM THE GATE'S OWN MEASUREMENT" });
    expect(measure).toHaveBeenCalledTimes(1);
    // The body is still read exactly once, and still never as JSON.
    expect(res.json).toHaveBeenCalledTimes(0);
    expect(res.text).toHaveBeenCalledTimes(1);
  });

  it("AC-54: with NO options at all, the attachment-presence default still decides", async () => {
    // Every existing caller in this file passes no options, and the production
    // call site (`runChatRequest`'s `readChatResponse(response, {...})`) is the
    // only one that knows better. That is
    // the contract `hasAttachments = true` exists to hold.
    const result = await chatbot.readChatResponse(RES_413());
    expect(result.ok).toBe(false);
    expect(result.error).toBe(chatbot.TOO_BIG_ATTACHMENTS_MESSAGE);
  });

  it("AC-54/AC-56: with hasAttachments false and no measurement, the HEDGED applications constant", async () => {
    // AMENDED FOR AC-56 (AC.md rev 5), and RED until the constant lands.
    //
    // This assertion previously named `TOO_BIG_APPLICATIONS_MESSAGE`. It was a
    // faithful test of AC-54 as it stood, and AC-54 has been superseded here:
    // the measured constant makes a FLAT causal claim ("most of it is your
    // saved application history"), which is earned on the gate's path -- there
    // we serialized the five sections and counted -- and unearned on THIS one,
    // which by definition measured nothing. `readChatResponse` has no body; on
    // this branch it knows only that the platform said 413 and that the tray
    // was empty. AC-55 already concedes our count and the platform's can
    // legitimately disagree, so a flat claim here asserts a cause nobody
    // established.
    //
    // The full ruling, the two negatives, and the paired positive control that
    // keeps the MEASURED path flat live in
    // lib/chat/chatbot.refusal.test.js's AC-56 describe. This case is the
    // second emitter's own copy of the identity, kept here because this file
    // is where `readChatResponse`'s fallback branches are pinned.
    const result = await chatbot.readChatResponse(RES_413(), { hasAttachments: false });
    expect(result.error).toBe(chatbot.TOO_BIG_APPLICATIONS_UNMEASURED_MESSAGE);
    expect(result.error).not.toBe(chatbot.TOO_BIG_APPLICATIONS_MESSAGE);
  });

  it("AC-54: a measurement that returns nothing falls back rather than showing an empty panel", async () => {
    // A builder that hit an empty payload, or a caller that passed a function
    // returning `undefined`, must not blank the message out.
    for (const empty of [() => "", () => null, () => undefined]) {
      const result = await chatbot.readChatResponse(RES_413(), {
        hasAttachments: true,
        refusalMessage: empty,
      });
      expect(result.error).toBe(chatbot.TOO_BIG_ATTACHMENTS_MESSAGE);
    }
  });

  it("B5: a measurement that THROWS never leaks a raw JS message into the chat window", async () => {
    // This function is exported and any caller can hand it a function that
    // throws -- `JSON.stringify` on a multi-megabyte payload really can raise
    // a RangeError. An escape here lands in runChatRequest's catch
    // (`runChatRequest`'s `catch (err)`) and prints the raw message to the user: exactly the
    // leak class this file's :97-119 header and commit af9ac29 exist to close.
    const boom = vi.fn(() => { throw new RangeError("Invalid string length"); });
    const result = await chatbot.readChatResponse(RES_413(), {
      hasAttachments: true,
      refusalMessage: boom,
    });

    expect(boom).toHaveBeenCalledTimes(1);
    expect(result.ok).toBe(false);
    // ABSENCE...
    expect(result.error).not.toMatch(/RangeError/i);
    expect(result.error).not.toMatch(/Invalid string length/i);
    // ...PAIRED with the POSITIVE CONTROL that makes the absence mean
    // something: what the user gets instead is AC-54's real fallback.
    expect(result.error).toBe(chatbot.TOO_BIG_ATTACHMENTS_MESSAGE);
  });

  it("a non-function `refusalMessage` is ignored rather than called", async () => {
    // AMENDED FOR AC-56 alongside the case above, and for the same reason: a
    // non-function measurement is NO measurement, so this lands on the
    // unmeasured branch and must read as the unmeasured branch. The thing
    // under test here is unchanged -- that a string/number/object/null is
    // ignored rather than invoked -- only the constant it falls back to moves.
    for (const bad of ["a string", 42, {}, null]) {
      const result = await chatbot.readChatResponse(RES_413(), {
        hasAttachments: false,
        refusalMessage: bad,
      });
      expect(result.error).toBe(chatbot.TOO_BIG_APPLICATIONS_UNMEASURED_MESSAGE);
    }
  });

  it("PAIRED POSITIVE CONTROL: no other status consults the measurement", async () => {
    // 413 is the only branch that may spend it. A 504 or a 500 asking for a
    // size measurement would be both wrong and expensive.
    const measure = vi.fn(() => "SHOULD NEVER BE USED");
    for (const status of [200, 400, 500, 502, 504, 408]) {
      const res = status === 200
        ? fakeJsonResponse({ status, payload: { reply: "hi" } })
        : fakeResponse({ status, body: "boom", contentType: undefined });
      const result = await chatbot.readChatResponse(res, { refusalMessage: measure });
      expect(result.error, `status ${status}`).not.toBe("SHOULD NEVER BE USED");
    }
    expect(measure).not.toHaveBeenCalled();
  });
});
