export const GREENHOUSE_COMPANIES = [
  { slug: "airbnb", name: "Airbnb" },
  { slug: "anthropic", name: "Anthropic" },
  { slug: "airtable", name: "Airtable" },
  { slug: "asana", name: "Asana" },
  { slug: "benchling", name: "Benchling" },
  { slug: "brex", name: "Brex" },
  { slug: "canva", name: "Canva" },
  { slug: "checkr", name: "Checkr" },
  { slug: "coinbase", name: "Coinbase" },
  { slug: "discord", name: "Discord" },
  { slug: "doordash", name: "DoorDash" },
  { slug: "dropbox", name: "Dropbox" },
  { slug: "duolingo", name: "Duolingo" },
  { slug: "figma", name: "Figma" },
  { slug: "gusto", name: "Gusto" },
  { slug: "lattice", name: "Lattice" },
  { slug: "lyft", name: "Lyft" },
  { slug: "notion", name: "Notion" },
  { slug: "pinterest", name: "Pinterest" },
  { slug: "plaid", name: "Plaid" },
  { slug: "reddit", name: "Reddit" },
  { slug: "rippling", name: "Rippling" },
  { slug: "robinhood", name: "Robinhood" },
  { slug: "scaleai", name: "Scale AI" },
  { slug: "stripe", name: "Stripe" },
  { slug: "twitch", name: "Twitch" },
  { slug: "zendesk", name: "Zendesk" },
];
