export const GREENHOUSE_COMPANIES = [
  { slug: "acorns", name: "Acorns", categories: ["Fintech"] },
  { slug: "affirm", name: "Affirm", categories: ["Fintech"] },
  { slug: "airbnb", name: "Airbnb", categories: ["Consumer"] },
  { slug: "airtable", name: "Airtable", categories: ["B2B SaaS"] },
  { slug: "algolia", name: "Algolia", categories: ["Dev Tools"] },
  { slug: "amplitude", name: "Amplitude", categories: ["Data & Analytics"] },
  { slug: "anthropic", name: "Anthropic", categories: ["AI & ML"] },
  { slug: "asana", name: "Asana", categories: ["B2B SaaS"] },
  { slug: "attentive", name: "Attentive", categories: ["B2B SaaS"] },
  { slug: "benchling", name: "Benchling", categories: ["Healthcare & Wellness"] },
  { slug: "betterment", name: "Betterment", categories: ["Fintech"] },
  { slug: "branch", name: "Branch", categories: ["Insurance"] },
  { slug: "braze", name: "Braze", categories: ["B2B SaaS"] },
  { slug: "brex", name: "Brex", categories: ["Fintech"] },
  { slug: "calm", name: "Calm", categories: ["Healthcare & Wellness"] },
  { slug: "canva", name: "Canva", categories: ["B2B SaaS"] },
  { slug: "carbonhealth", name: "Carbon Health", categories: ["Healthcare & Wellness"] },
  { slug: "carta", name: "Carta", categories: ["Fintech"] },
  { slug: "cedar", name: "Cedar", categories: ["Healthcare & Wellness"] },
  { slug: "chainalysis", name: "Chainalysis", categories: ["Cybersecurity"] },
  { slug: "checkr", name: "Checkr", categories: ["B2B SaaS"] },
  { slug: "chime", name: "Chime", categories: ["Fintech"] },
  { slug: "cityblock", name: "Cityblock Health", categories: ["Healthcare & Wellness"] },
  { slug: "cockroachlabs", name: "CockroachLabs", categories: ["Infrastructure & DevOps"] },
  { slug: "coinbase", name: "Coinbase", categories: ["Fintech"] },
  { slug: "color", name: "Color Health", categories: ["Healthcare & Wellness"] },
  { slug: "confluent", name: "Confluent", categories: ["Infrastructure & DevOps"] },
  { slug: "contentful", name: "Contentful", categories: ["B2B SaaS"] },
  { slug: "cribl", name: "Cribl", categories: ["Infrastructure & DevOps"] },
  { slug: "crowdstrike", name: "CrowdStrike", categories: ["Cybersecurity"] },
  { slug: "databricks", name: "Databricks", categories: ["Data & Analytics"] },
  { slug: "dave", name: "Dave", categories: ["Fintech"] },
  { slug: "deel", name: "Deel", categories: ["B2B SaaS"] },
  { slug: "devoted", name: "Devoted Health", categories: ["Healthcare & Wellness"] },
  { slug: "discord", name: "Discord", categories: ["Consumer"] },
  { slug: "doordash", name: "DoorDash", categories: ["Consumer"] },
  { slug: "dropbox", name: "Dropbox", categories: ["B2B SaaS"] },
  { slug: "duolingo", name: "Duolingo", categories: ["Consumer"] },
  { slug: "elastic", name: "Elastic", categories: ["Infrastructure & DevOps"] },
  { slug: "eventbrite", name: "Eventbrite", categories: ["Consumer"] },
  { slug: "faire", name: "Faire", categories: ["B2B SaaS"] },
  { slug: "figma", name: "Figma", categories: ["B2B SaaS"] },
  { slug: "figure", name: "Figure", categories: ["Fintech"] },
  { slug: "flatiron", name: "Flatiron Health", categories: ["Healthcare & Wellness"] },
  { slug: "flexport", name: "Flexport", categories: ["B2B SaaS"] },
  { slug: "frontapp", name: "Front", categories: ["B2B SaaS"] },
  { slug: "gitlab", name: "GitLab", categories: ["Dev Tools"] },
  { slug: "grammarly", name: "Grammarly", categories: ["B2B SaaS"] },
  { slug: "grafana", name: "Grafana Labs", categories: ["Infrastructure & DevOps"] },
  { slug: "guideline", name: "Guideline", categories: ["Fintech"] },
  { slug: "gusto", name: "Gusto", categories: ["Fintech"] },
  { slug: "hackerone", name: "HackerOne", categories: ["Cybersecurity"] },
  { slug: "hashicorp", name: "HashiCorp", categories: ["Infrastructure & DevOps"] },
  { slug: "heap", name: "Heap", categories: ["Data & Analytics"] },
  { slug: "highspot", name: "Highspot", categories: ["B2B SaaS"] },
  { slug: "hippo", name: "Hippo", categories: ["Insurance"] },
  { slug: "hubspot", name: "HubSpot", categories: ["B2B SaaS"] },
  { slug: "includedhealth", name: "Included Health", categories: ["Healthcare & Wellness"] },
  { slug: "instacart", name: "Instacart", categories: ["Consumer"] },
  { slug: "intercom", name: "Intercom", categories: ["B2B SaaS"] },
  { slug: "iterable", name: "Iterable", categories: ["B2B SaaS"] },
  { slug: "kin", name: "Kin Insurance", categories: ["Insurance"] },
  { slug: "klaviyo", name: "Klaviyo", categories: ["B2B SaaS"] },
  { slug: "komodohealth", name: "Komodo Health", categories: ["Healthcare & Wellness"] },
  { slug: "launchdarkly", name: "LaunchDarkly", categories: ["Dev Tools"] },
  { slug: "lattice", name: "Lattice", categories: ["B2B SaaS"] },
  { slug: "lemonade", name: "Lemonade", categories: ["Insurance"] },
  { slug: "linear", name: "Linear", categories: ["Dev Tools"] },
  { slug: "lob", name: "Lob", categories: ["Dev Tools"] },
  { slug: "loom", name: "Loom", categories: ["B2B SaaS"] },
  { slug: "lyft", name: "Lyft", categories: ["Consumer"] },
  { slug: "lyrahealth", name: "Lyra Health", categories: ["Healthcare & Wellness"] },
  { slug: "marqeta", name: "Marqeta", categories: ["Fintech"] },
  { slug: "mavenclinic", name: "Maven Clinic", categories: ["Healthcare & Wellness"] },
  { slug: "mercury", name: "Mercury", categories: ["Fintech"] },
  { slug: "miro", name: "Miro", categories: ["B2B SaaS"] },
  { slug: "mixpanel", name: "Mixpanel", categories: ["Data & Analytics"] },
  { slug: "modernhealth", name: "Modern Health", categories: ["Healthcare & Wellness"] },
  { slug: "mongodb", name: "MongoDB", categories: ["Infrastructure & DevOps"] },
  { slug: "navan", name: "Navan", categories: ["B2B SaaS"] },
  { slug: "nextdoor", name: "Nextdoor", categories: ["Consumer"] },
  { slug: "nextinsurance", name: "Next Insurance", categories: ["Insurance"] },
  { slug: "noom", name: "Noom", categories: ["Healthcare & Wellness"] },
  { slug: "notion", name: "Notion", categories: ["B2B SaaS"] },
  { slug: "nubank", name: "Nubank", categories: ["Fintech"] },
  { slug: "okta", name: "Okta", categories: ["Cybersecurity"] },
  { slug: "oscar", name: "Oscar Health", categories: ["Insurance"] },
  { slug: "pagerduty", name: "PagerDuty", categories: ["Infrastructure & DevOps"] },
  { slug: "patreon", name: "Patreon", categories: ["Consumer"] },
  { slug: "payoneer", name: "Payoneer", categories: ["Fintech"] },
  { slug: "pendo", name: "Pendo", categories: ["B2B SaaS"] },
  { slug: "pinterest", name: "Pinterest", categories: ["Consumer"] },
  { slug: "plaid", name: "Plaid", categories: ["Fintech"] },
  { slug: "podium", name: "Podium", categories: ["B2B SaaS"] },
  { slug: "policygenius", name: "Policygenius", categories: ["Insurance"] },
  { slug: "postman", name: "Postman", categories: ["Dev Tools"] },
  { slug: "productboard", name: "Productboard", categories: ["B2B SaaS"] },
  { slug: "ramp", name: "Ramp", categories: ["Fintech"] },
  { slug: "reddit", name: "Reddit", categories: ["Consumer"] },
  { slug: "redfin", name: "Redfin", categories: ["Consumer"] },
  { slug: "retool", name: "Retool", categories: ["Dev Tools"] },
  { slug: "rippling", name: "Rippling", categories: ["B2B SaaS"] },
  { slug: "ro", name: "Ro", categories: ["Healthcare & Wellness"] },
  { slug: "robinhood", name: "Robinhood", categories: ["Fintech"] },
  { slug: "roblox", name: "Roblox", categories: ["Consumer"] },
  { slug: "root", name: "Root Insurance", categories: ["Insurance"] },
  { slug: "scaleai", name: "Scale AI", categories: ["AI & ML"] },
  { slug: "segment", name: "Segment", categories: ["Data & Analytics"] },
  { slug: "sentry", name: "Sentry", categories: ["Dev Tools"] },
  { slug: "shippo", name: "Shippo", categories: ["B2B SaaS"] },
  { slug: "sigmacomputing", name: "Sigma Computing", categories: ["Data & Analytics"] },
  { slug: "singlestore", name: "SingleStore", categories: ["Infrastructure & DevOps"] },
  { slug: "snowflake", name: "Snowflake", categories: ["Data & Analytics"] },
  { slug: "snyk", name: "Snyk", categories: ["Cybersecurity"] },
  { slug: "sofi", name: "SoFi", categories: ["Fintech"] },
  { slug: "sourcegraph", name: "Sourcegraph", categories: ["Dev Tools"] },
  { slug: "springhealth", name: "Spring Health", categories: ["Healthcare & Wellness"] },
  { slug: "sprinklr", name: "Sprinklr", categories: ["B2B SaaS"] },
  { slug: "stash", name: "Stash", categories: ["Fintech"] },
  { slug: "strava", name: "Strava", categories: ["Consumer"] },
  { slug: "stripe", name: "Stripe", categories: ["Fintech"] },
  { slug: "superhuman", name: "Superhuman", categories: ["B2B SaaS"] },
  { slug: "temporal", name: "Temporal", categories: ["Infrastructure & DevOps"] },
  { slug: "tempus", name: "Tempus", categories: ["Healthcare & Wellness"] },
  { slug: "toasttab", name: "Toast", categories: ["B2B SaaS"] },
  { slug: "twitch", name: "Twitch", categories: ["Consumer"] },
  { slug: "upgrade", name: "Upgrade", categories: ["Fintech"] },
  { slug: "vanta", name: "Vanta", categories: ["Cybersecurity"] },
  { slug: "vercel", name: "Vercel", categories: ["Dev Tools"] },
  { slug: "verkada", name: "Verkada", categories: ["Cybersecurity"] },
  { slug: "vestwell", name: "Vestwell", categories: ["Fintech"] },
  { slug: "vimeo", name: "Vimeo", categories: ["Consumer"] },
  { slug: "vouch", name: "Vouch", categories: ["Insurance"] },
  { slug: "wandb", name: "Weights & Biases", categories: ["AI & ML"] },
  { slug: "wealthfront", name: "Wealthfront", categories: ["Fintech"] },
  { slug: "webflow", name: "Webflow", categories: ["Dev Tools"] },
  { slug: "whatnot", name: "Whatnot", categories: ["Consumer"] },
  { slug: "wise", name: "Wise", categories: ["Fintech"] },
  { slug: "wiz", name: "Wiz", categories: ["Cybersecurity"] },
  { slug: "workos", name: "WorkOS", categories: ["Dev Tools"] },
  { slug: "zapier", name: "Zapier", categories: ["B2B SaaS"] },
  { slug: "zendesk", name: "Zendesk", categories: ["B2B SaaS"] },
  { slug: "zocdoc", name: "Zocdoc", categories: ["Healthcare & Wellness"] },
];

export const COMPANY_CATEGORIES = [
  ...new Set(GREENHOUSE_COMPANIES.flatMap((c) => c.categories)),
].sort();
  { slug: "airbnb", name: "Airbnb" },
