export const GREENHOUSE_COMPANIES = [
  { slug: "acorns", name: "Acorns", categories: ["Fintech"] },
  { slug: "affirm", name: "Affirm", categories: ["Fintech"] },
  { slug: "airbnb", name: "Airbnb", categories: ["Consumer"] },
  { slug: "airtable", name: "Airtable", categories: ["B2B SaaS"] },
  { slug: "algolia", name: "Algolia", categories: ["Dev Tools"] },
  { slug: "amplitude", name: "Amplitude", categories: ["Data & Analytics"] },
  { slug: "anthropic", name: "Anthropic", categories: ["AI & ML"] },
  { slug: "asana", name: "Asana", categories: ["B2B SaaS"] },
  { slug: "attentive", name: "Attentive", categories: ["B2B SaaS"] },
  { slug: "benchling", name: "Benchling", categories: ["Healthcare & Wellness"] },
  { slug: "betterment", name: "Betterment", categories: ["Fintech"] },
  { slug: "branch", name: "Branch", categories: ["Insurance"] },
  { slug: "braze", name: "Braze", categories: ["B2B SaaS"] },
  { slug: "brex", name: "Brex", categories: ["Fintech"] },
  { slug: "calm", name: "Calm", categories: ["Healthcare & Wellness"] },
  { slug: "canva", name: "Canva", categories: ["B2B SaaS"] },
  { slug: "carbonhealth", name: "Carbon Health", categories: ["Healthcare & Wellness"] },
  { slug: "carta", name: "Carta", categories: ["Fintech"] },
  { slug: "cedar", name: "Cedar", categories: ["Healthcare & Wellness"] },
  { slug: "chainalysis", name: "Chainalysis", categories: ["Cybersecurity"] },
  { slug: "checkr", name: "Checkr", categories: ["B2B SaaS"] },
  { slug: "chime", name: "Chime", categories: ["Fintech"] },
  { slug: "cityblock", name: "Cityblock Health", categories: ["Healthcare & Wellness"] },
  { slug: "cockroachlabs", name: "CockroachLabs", categories: ["Infrastructure & DevOps"] },
  { slug: "coinbase", name: "Coinbase", categories: ["Fintech"] },
  { slug: "color", name: "Color Health", categories: ["Healthcare & Wellness"] },
  { slug: "confluent", name: "Confluent", categories: ["Infrastructure & DevOps"] },
  { slug: "contentful", name: "Contentful", categories: ["B2B SaaS"] },
  { slug: "cribl", name: "Cribl", categories: ["Infrastructure & DevOps"] },
  { slug: "crowdstrike", name: "CrowdStrike", categories: ["Cybersecurity"] },
  { slug: "databricks", name: "Databricks", categories: ["Data & Analytics"] },
  { slug: "dave", name: "Dave", categories: ["Fintech"] },
  { slug: "deel", name: "Deel", categories: ["B2B SaaS"] },
  { slug: "devoted", name: "Devoted Health", categories: ["Healthcare & Wellness"] },
  { slug: "discord", name: "Discord", categories: ["Consumer"] },
  { slug: "doordash", name: "DoorDash", categories: ["Consumer"] },
  { slug: "dropbox", name: "Dropbox", categories: ["B2B SaaS"] },
  { slug: "duolingo", name: "Duolingo", categories: ["Consumer"] },
  { slug: "elastic", name: "Elastic", categories: ["Infrastructure & DevOps"] },
  { slug: "eventbrite", name: "Eventbrite", categories: ["Consumer"] },
  { slug: "faire", name: "Faire", categories: ["B2B SaaS"] },
  { slug: "figma", name: "Figma", categories: ["B2B SaaS"] },
  { slug: "figure", name: "Figure", categories: ["Fintech"] },
  { slug: "flatiron", name: "Flatiron Health", categories: ["Healthcare & Wellness"] },
  { slug: "flexport", name: "Flexport", categories: ["B2B SaaS"] },
  { slug: "frontapp", name: "Front", categories: ["B2B SaaS"] },
  { slug: "gitlab", name: "GitLab", categories: ["Dev Tools"] },
  { slug: "grammarly", name: "Grammarly", categories: ["B2B SaaS"] },
  { slug: "grafana", name: "Grafana Labs", categories: ["Infrastructure & DevOps"] },
  { slug: "guideline", name: "Guideline", categories: ["Fintech"] },
  { slug: "gusto", name: "Gusto", categories: ["Fintech"] },
  { slug: "hackerone", name: "HackerOne", categories: ["Cybersecurity"] },
  { slug: "hashicorp", name: "HashiCorp", categories: ["Infrastructure & DevOps"] },
  { slug: "heap", name: "Heap", categories: ["Data & Analytics"] },
  { slug: "highspot", name: "Highspot", categories: ["B2B SaaS"] },
  { slug: "hippo", name: "Hippo", categories: ["Insurance"] },
  { slug: "hubspot", name: "HubSpot", categories: ["B2B SaaS"] },
  { slug: "includedhealth", name: "Included Health", categories: ["Healthcare & Wellness"] },
  { slug: "instacart", name: "Instacart", categories: ["Consumer"] },
  { slug: "intercom", name: "Intercom", categories: ["B2B SaaS"] },
  { slug: "iterable", name: "Iterable", categories: ["B2B SaaS"] },
  { slug: "kin", name: "Kin Insurance", categories: ["Insurance"] },
  { slug: "klaviyo", name: "Klaviyo", categories: ["B2B SaaS"] },
  { slug: "komodohealth", name: "Komodo Health", categories: ["Healthcare & Wellness"] },
  { slug: "launchdarkly", name: "LaunchDarkly", categories: ["Dev Tools"] },
  { slug: "lattice", name: "Lattice", categories: ["B2B SaaS"] },
  { slug: "lemonade", name: "Lemonade", categories: ["Insurance"] },
  { slug: "linear", name: "Linear", categories: ["Dev Tools"] },
  { slug: "lob", name: "Lob", categories: ["Dev Tools"] },
  { slug: "loom", name: "Loom", categories: ["B2B SaaS"] },
  { slug: "lyft", name: "Lyft", categories: ["Consumer"] },
  { slug: "lyrahealth", name: "Lyra Health", categories: ["Healthcare & Wellness"] },
  { slug: "marqeta", name: "Marqeta", categories: ["Fintech"] },
  { slug: "mavenclinic", name: "Maven Clinic", categories: ["Healthcare & Wellness"] },
  { slug: "mercury", name: "Mercury", categories: ["Fintech"] },
  { slug: "miro", name: "Miro", categories: ["B2B SaaS"] },
  { slug: "mixpanel", name: "Mixpanel", categories: ["Data & Analytics"] },
  { slug: "modernhealth", name: "Modern Health", categories: ["Healthcare & Wellness"] },
  { slug: "mongodb", name: "MongoDB", categories: ["Infrastructure & DevOps"] },
  { slug: "navan", name: "Navan", categories: ["B2B SaaS"] },
  { slug: "nextdoor", name: "Nextdoor", categories: ["Consumer"] },
  { slug: "nextinsurance", name: "Next Insurance", categories: ["Insurance"] },
  { slug: "noom", name: "Noom", categories: ["Healthcare & Wellness"] },
  { slug: "notion", name: "Notion", categories: ["B2B SaaS"] },
  { slug: "nubank", name: "Nubank", categories: ["Fintech"] },
  { slug: "okta", name: "Okta", categories: ["Cybersecurity"] },
  { slug: "oscar", name: "Oscar Health", categories: ["Insurance"] },
  { slug: "pagerduty", name: "PagerDuty", categories: ["Infrastructure & DevOps"] },
  { slug: "patreon", name: "Patreon", categories: ["Consumer"] },
  { slug: "payoneer", name: "Payoneer", categories: ["Fintech"] },
  { slug: "pendo", name: "Pendo", categories: ["B2B SaaS"] },
  { slug: "pinterest", name: "Pinterest", categories: ["Consumer"] },
  { slug: "plaid", name: "Plaid", categories: ["Fintech"] },
  { slug: "podium", name: "Podium", categories: ["B2B SaaS"] },
  { slug: "policygenius", name: "Policygenius", categories: ["Insurance"] },
  { slug: "postman", name: "Postman", categories: ["Dev Tools"] },
  { slug: "productboard", name: "Productboard", categories: ["B2B SaaS"] },
  { slug: "ramp", name: "Ramp", categories: ["Fintech"] },
  { slug: "reddit", name: "Reddit", categories: ["Consumer"] },
  { slug: "redfin", name: "Redfin", categories: ["Consumer"] },
  { slug: "retool", name: "Retool", categories: ["Dev Tools"] },
  { slug: "rippling", name: "Rippling", categories: ["B2B SaaS"] },
  { slug: "ro", name: "Ro", categories: ["Healthcare & Wellness"] },
  { slug: "robinhood", name: "Robinhood", categories: ["Fintech"] },
  { slug: "roblox", name: "Roblox", categories: ["Consumer"] },
  { slug: "root", name: "Root Insurance", categories: ["Insurance"] },
  { slug: "scaleai", name: "Scale AI", categories: ["AI & ML"] },
  { slug: "segment", name: "Segment", categories: ["Data & Analytics"] },
  { slug: "sentry", name: "Sentry", categories: ["Dev Tools"] },
  { slug: "shippo", name: "Shippo", categories: ["B2B SaaS"] },
  { slug: "sigmacomputing", name: "Sigma Computing", categories: ["Data & Analytics"] },
  { slug: "singlestore", name: "SingleStore", categories: ["Infrastructure & DevOps"] },
  { slug: "snowflake", name: "Snowflake", categories: ["Data & Analytics"] },
  { slug: "snyk", name: "Snyk", categories: ["Cybersecurity"] },
  { slug: "sofi", name: "SoFi", categories: ["Fintech"] },
  { slug: "sourcegraph", name: "Sourcegraph", categories: ["Dev Tools"] },
  { slug: "springhealth", name: "Spring Health", categories: ["Healthcare & Wellness"] },
  { slug: "sprinklr", name: "Sprinklr", categories: ["B2B SaaS"] },
  { slug: "stash", name: "Stash", categories: ["Fintech"] },
  { slug: "strava", name: "Strava", categories: ["Consumer"] },
  { slug: "stripe", name: "Stripe", categories: ["Fintech"] },
  { slug: "superhuman", name: "Superhuman", categories: ["B2B SaaS"] },
  { slug: "temporal", name: "Temporal", categories: ["Infrastructure & DevOps"] },
  { slug: "tempus", name: "Tempus", categories: ["Healthcare & Wellness"] },
  { slug: "toasttab", name: "Toast", categories: ["B2B SaaS"] },
  { slug: "twitch", name: "Twitch", categories: ["Consumer"] },
  { slug: "upgrade", name: "Upgrade", categories: ["Fintech"] },
  { slug: "vanta", name: "Vanta", categories: ["Cybersecurity"] },
  { slug: "vercel", name: "Vercel", categories: ["Dev Tools"] },
  { slug: "verkada", name: "Verkada", categories: ["Cybersecurity"] },
  { slug: "vestwell", name: "Vestwell", categories: ["Fintech"] },
  { slug: "vimeo", name: "Vimeo", categories: ["Consumer"] },
  { slug: "vouch", name: "Vouch", categories: ["Insurance"] },
  { slug: "wandb", name: "Weights & Biases", categories: ["AI & ML"] },
  { slug: "wealthfront", name: "Wealthfront", categories: ["Fintech"] },
  { slug: "webflow", name: "Webflow", categories: ["Dev Tools"] },
  { slug: "whatnot", name: "Whatnot", categories: ["Consumer"] },
  { slug: "wise", name: "Wise", categories: ["Fintech"] },
  { slug: "wiz", name: "Wiz", categories: ["Cybersecurity"] },
  { slug: "workos", name: "WorkOS", categories: ["Dev Tools"] },
  { slug: "zapier", name: "Zapier", categories: ["B2B SaaS"] },
  { slug: "zendesk", name: "Zendesk", categories: ["B2B SaaS"] },
  { slug: "zocdoc", name: "Zocdoc", categories: ["Healthcare & Wellness"] },

  // AI & ML (expanded)
  { slug: "openai", name: "OpenAI", categories: ["AI & ML"] },
  { slug: "cohere", name: "Cohere", categories: ["AI & ML"] },
  { slug: "runway", name: "Runway", categories: ["AI & ML"] },
  { slug: "adept", name: "Adept", categories: ["AI & ML"] },
  { slug: "perplexityai", name: "Perplexity AI", categories: ["AI & ML"] },
  { slug: "harvey", name: "Harvey", categories: ["AI & ML", "Legal Tech"] },
  { slug: "cognition", name: "Cognition", categories: ["AI & ML"] },
  { slug: "mistral", name: "Mistral AI", categories: ["AI & ML"] },
  { slug: "together", name: "Together AI", categories: ["AI & ML"] },
  { slug: "anyscale", name: "Anyscale", categories: ["AI & ML", "Infrastructure & DevOps"] },
  { slug: "mosaic", name: "MosaicML", categories: ["AI & ML"] },
  { slug: "twelvelabs", name: "Twelve Labs", categories: ["AI & ML"] },
  { slug: "cleanlab", name: "Cleanlab", categories: ["AI & ML", "Data & Analytics"] },

  // Fintech (expanded)
  { slug: "klarna", name: "Klarna", categories: ["Fintech"] },
  { slug: "revolut", name: "Revolut", categories: ["Fintech"] },
  { slug: "monzo", name: "Monzo", categories: ["Fintech"] },
  { slug: "n26", name: "N26", categories: ["Fintech"] },
  { slug: "adyen", name: "Adyen", categories: ["Fintech"] },
  { slug: "tala", name: "Tala", categories: ["Fintech"] },
  { slug: "greenlight", name: "Greenlight", categories: ["Fintech"] },
  { slug: "karat", name: "Karat", categories: ["Fintech"] },
  { slug: "aeropay", name: "AeroPay", categories: ["Fintech"] },
  { slug: "pipe", name: "Pipe", categories: ["Fintech"] },
  { slug: "lithic", name: "Lithic", categories: ["Fintech"] },
  { slug: "check", name: "Check", categories: ["Fintech"] },

  // Consumer (expanded)
  { slug: "bumble", name: "Bumble", categories: ["Consumer"] },
  { slug: "hinge", name: "Hinge", categories: ["Consumer"] },
  { slug: "peloton", name: "Peloton", categories: ["Consumer"] },
  { slug: "gofundme", name: "GoFundMe", categories: ["Consumer"] },
  { slug: "grubhub", name: "Grubhub", categories: ["Consumer"] },
  { slug: "bereal", name: "BeReal", categories: ["Consumer"] },
  { slug: "clubhouse", name: "Clubhouse", categories: ["Consumer"] },
  { slug: "tiktok", name: "TikTok", categories: ["Consumer"] },
  { slug: "snap", name: "Snap", categories: ["Consumer"] },

  // Gaming
  { slug: "niantic", name: "Niantic", categories: ["Gaming"] },
  { slug: "scopely", name: "Scopely", categories: ["Gaming"] },
  { slug: "zynga", name: "Zynga", categories: ["Gaming"] },
  { slug: "unity", name: "Unity Technologies", categories: ["Gaming", "Dev Tools"] },
  { slug: "riotgames", name: "Riot Games", categories: ["Gaming"] },
  { slug: "epicgames", name: "Epic Games", categories: ["Gaming"] },
  { slug: "playtika", name: "Playtika", categories: ["Gaming"] },
  { slug: "jam-city", name: "Jam City", categories: ["Gaming"] },
  { slug: "genvid", name: "Genvid", categories: ["Gaming"] },
  { slug: "overwolf", name: "Overwolf", categories: ["Gaming"] },
  { slug: "agora", name: "Agora", categories: ["Gaming", "Infrastructure & DevOps"] },
  { slug: "playstudios", name: "PlayStudios", categories: ["Gaming"] },

  // EdTech
  { slug: "coursera", name: "Coursera", categories: ["EdTech"] },
  { slug: "masterclass", name: "MasterClass", categories: ["EdTech"] },
  { slug: "udemy", name: "Udemy", categories: ["EdTech"] },
  { slug: "pluralsight", name: "Pluralsight", categories: ["EdTech"] },
  { slug: "kahoot", name: "Kahoot", categories: ["EdTech"] },
  { slug: "chegg", name: "Chegg", categories: ["EdTech"] },
  { slug: "skillshare", name: "Skillshare", categories: ["EdTech"] },
  { slug: "instructure", name: "Instructure", categories: ["EdTech"] },
  { slug: "outlier", name: "Outlier", categories: ["EdTech"] },
  { slug: "learnerbly", name: "Learnerbly", categories: ["EdTech"] },
  { slug: "synthesis", name: "Synthesis", categories: ["EdTech"] },
  { slug: "quizlet", name: "Quizlet", categories: ["EdTech"] },

  // Real Estate
  { slug: "opendoor", name: "Opendoor", categories: ["Real Estate"] },
  { slug: "compass", name: "Compass", categories: ["Real Estate"] },
  { slug: "fundrise", name: "Fundrise", categories: ["Real Estate"] },
  { slug: "roofstock", name: "Roofstock", categories: ["Real Estate"] },
  { slug: "pacaso", name: "Pacaso", categories: ["Real Estate"] },
  { slug: "homeward", name: "Homeward", categories: ["Real Estate"] },
  { slug: "doorstead", name: "Doorstead", categories: ["Real Estate"] },
  { slug: "divvyhomes", name: "Divvy Homes", categories: ["Real Estate", "Fintech"] },
  { slug: "landis", name: "Landis", categories: ["Real Estate", "Fintech"] },
  { slug: "arrived", name: "Arrived Homes", categories: ["Real Estate", "Fintech"] },
  { slug: "knock", name: "Knock", categories: ["Real Estate"] },
  { slug: "flyhomes", name: "Flyhomes", categories: ["Real Estate"] },

  // Transportation & Logistics
  { slug: "samsara", name: "Samsara", categories: ["Transportation & Logistics"] },
  { slug: "motive", name: "Motive", categories: ["Transportation & Logistics"] },
  { slug: "project44", name: "project44", categories: ["Transportation & Logistics"] },
  { slug: "loadsmart", name: "Loadsmart", categories: ["Transportation & Logistics"] },
  { slug: "transfix", name: "Transfix", categories: ["Transportation & Logistics"] },
  { slug: "gatik", name: "Gatik", categories: ["Transportation & Logistics", "AI & ML"] },
  { slug: "nuro", name: "Nuro", categories: ["Transportation & Logistics", "AI & ML"] },
  { slug: "aurora", name: "Aurora", categories: ["Transportation & Logistics", "AI & ML"] },
  { slug: "torc", name: "Torc Robotics", categories: ["Transportation & Logistics", "AI & ML"] },
  { slug: "ownbackup", name: "OwnBackup", categories: ["Transportation & Logistics"] },
  { slug: "stord", name: "Stord", categories: ["Transportation & Logistics"] },
  { slug: "bringg", name: "Bringg", categories: ["Transportation & Logistics"] },

  // HR Tech
  { slug: "ashby", name: "Ashby", categories: ["HR Tech"] },
  { slug: "leapsome", name: "Leapsome", categories: ["HR Tech"] },
  { slug: "hibob", name: "HiBob", categories: ["HR Tech"] },
  { slug: "personio", name: "Personio", categories: ["HR Tech"] },
  { slug: "remote", name: "Remote", categories: ["HR Tech"] },
  { slug: "oysterhr", name: "Oyster HR", categories: ["HR Tech"] },
  { slug: "workramp", name: "WorkRamp", categories: ["HR Tech"] },
  { slug: "cultureamp", name: "Culture Amp", categories: ["HR Tech"] },
  { slug: "betterworks", name: "BetterWorks", categories: ["HR Tech"] },
  { slug: "15five", name: "15Five", categories: ["HR Tech"] },
  { slug: "pave", name: "Pave", categories: ["HR Tech", "Fintech"] },
  { slug: "forma", name: "Forma", categories: ["HR Tech"] },
  { slug: "checkr", name: "Checkr", categories: ["HR Tech"] },
  { slug: "lever", name: "Lever", categories: ["HR Tech"] },

  // Legal Tech
  { slug: "ironclad", name: "Ironclad", categories: ["Legal Tech"] },
  { slug: "clio", name: "Clio", categories: ["Legal Tech"] },
  { slug: "lexion", name: "Lexion", categories: ["Legal Tech"] },
  { slug: "evisort", name: "Evisort", categories: ["Legal Tech"] },
  { slug: "spellbook", name: "Spellbook", categories: ["Legal Tech", "AI & ML"] },
  { slug: "contractbook", name: "Contractbook", categories: ["Legal Tech"] },
  { slug: "linksquares", name: "LinkSquares", categories: ["Legal Tech"] },
  { slug: "simplelegal", name: "SimpleLegal", categories: ["Legal Tech"] },
  { slug: "onit", name: "Onit", categories: ["Legal Tech"] },
  { slug: "disco", name: "DISCO", categories: ["Legal Tech"] },

  // Climate Tech
  { slug: "aurorasolar", name: "Aurora Solar", categories: ["Climate Tech"] },
  { slug: "arcadia", name: "Arcadia", categories: ["Climate Tech"] },
  { slug: "crusoe", name: "Crusoe Energy", categories: ["Climate Tech"] },
  { slug: "sunrun", name: "Sunrun", categories: ["Climate Tech"] },
  { slug: "stem", name: "Stem", categories: ["Climate Tech"] },
  { slug: "pachama", name: "Pachama", categories: ["Climate Tech"] },
  { slug: "watershed", name: "Watershed", categories: ["Climate Tech"] },
  { slug: "xpansiv", name: "Xpansiv", categories: ["Climate Tech"] },
  { slug: "energyvault", name: "Energy Vault", categories: ["Climate Tech"] },
  { slug: "form-energy", name: "Form Energy", categories: ["Climate Tech"] },
  { slug: "electra", name: "Electra", categories: ["Climate Tech"] },
  { slug: "heirloom", name: "Heirloom Carbon", categories: ["Climate Tech"] },
  { slug: "charm", name: "Charm Industrial", categories: ["Climate Tech"] },

  // Blockchain & Web3
  { slug: "opensea", name: "OpenSea", categories: ["Blockchain & Web3"] },
  { slug: "alchemy", name: "Alchemy", categories: ["Blockchain & Web3"] },
  { slug: "consensys", name: "ConsenSys", categories: ["Blockchain & Web3"] },
  { slug: "blockdaemon", name: "Blockdaemon", categories: ["Blockchain & Web3"] },
  { slug: "anchorage", name: "Anchorage Digital", categories: ["Blockchain & Web3", "Fintech"] },
  { slug: "gemini", name: "Gemini", categories: ["Blockchain & Web3", "Fintech"] },
  { slug: "circle", name: "Circle", categories: ["Blockchain & Web3", "Fintech"] },
  { slug: "paxos", name: "Paxos", categories: ["Blockchain & Web3", "Fintech"] },
  { slug: "fireblocks", name: "Fireblocks", categories: ["Blockchain & Web3", "Cybersecurity"] },
  { slug: "bitgo", name: "BitGo", categories: ["Blockchain & Web3", "Fintech"] },
  { slug: "dfinity", name: "DFINITY", categories: ["Blockchain & Web3"] },
  { slug: "celestia", name: "Celestia", categories: ["Blockchain & Web3"] },

  // E-commerce
  { slug: "poshmark", name: "Poshmark", categories: ["E-commerce"] },
  { slug: "mercari", name: "Mercari", categories: ["E-commerce"] },
  { slug: "depop", name: "Depop", categories: ["E-commerce"] },
  { slug: "reverb", name: "Reverb", categories: ["E-commerce"] },
  { slug: "goat", name: "GOAT", categories: ["E-commerce"] },
  { slug: "stockx", name: "StockX", categories: ["E-commerce"] },
  { slug: "thredup", name: "ThredUp", categories: ["E-commerce"] },
  { slug: "offerup", name: "OfferUp", categories: ["E-commerce"] },
  { slug: "1stdibs", name: "1stDibs", categories: ["E-commerce"] },
  { slug: "vroom", name: "Vroom", categories: ["E-commerce"] },
  { slug: "carvana", name: "Carvana", categories: ["E-commerce"] },
  { slug: "fashionphile", name: "Fashionphile", categories: ["E-commerce"] },
  { slug: "rebag", name: "Rebag", categories: ["E-commerce"] },

  // Media & Entertainment
  { slug: "spotify", name: "Spotify", categories: ["Media & Entertainment"] },
  { slug: "buzzfeed", name: "BuzzFeed", categories: ["Media & Entertainment"] },
  { slug: "substack", name: "Substack", categories: ["Media & Entertainment"] },
  { slug: "cameo", name: "Cameo", categories: ["Media & Entertainment"] },
  { slug: "soundcloud", name: "SoundCloud", categories: ["Media & Entertainment"] },
  { slug: "audiomack", name: "Audiomack", categories: ["Media & Entertainment"] },
  { slug: "beehiiv", name: "beehiiv", categories: ["Media & Entertainment"] },
  { slug: "acast", name: "Acast", categories: ["Media & Entertainment"] },
  { slug: "chartable", name: "Chartable", categories: ["Media & Entertainment", "Data & Analytics"] },
  { slug: "fandom", name: "Fandom", categories: ["Media & Entertainment"] },
  { slug: "thingtesting", name: "Thingtesting", categories: ["Media & Entertainment"] },

  // Food Tech
  { slug: "impossiblefoods", name: "Impossible Foods", categories: ["Food Tech"] },
  { slug: "sweetgreen", name: "Sweetgreen", categories: ["Food Tech"] },
  { slug: "notco", name: "NotCo", categories: ["Food Tech"] },
  { slug: "misfitsmarket", name: "Misfits Market", categories: ["Food Tech"] },
  { slug: "hungryroot", name: "Hungryroot", categories: ["Food Tech"] },
  { slug: "oishii", name: "Oishii", categories: ["Food Tech"] },
  { slug: "apeel", name: "Apeel Sciences", categories: ["Food Tech", "Climate Tech"] },
  { slug: "everytable", name: "Everytable", categories: ["Food Tech"] },
  { slug: "farmer-bn", name: "Farmer's Business Network", categories: ["Food Tech"] },
  { slug: "choco", name: "Choco", categories: ["Food Tech"] },

  // Travel & Hospitality
  { slug: "hopper", name: "Hopper", categories: ["Travel & Hospitality"] },
  { slug: "sonder", name: "Sonder", categories: ["Travel & Hospitality"] },
  { slug: "getaround", name: "Getaround", categories: ["Travel & Hospitality"] },
  { slug: "vacasa", name: "Vacasa", categories: ["Travel & Hospitality"] },
  { slug: "spotnana", name: "Spotnana", categories: ["Travel & Hospitality"] },
  { slug: "flightright", name: "Flightright", categories: ["Travel & Hospitality"] },
  { slug: "stay22", name: "Stay22", categories: ["Travel & Hospitality"] },
  { slug: "tourradar", name: "TourRadar", categories: ["Travel & Hospitality"] },
  { slug: "outdoorsy", name: "Outdoorsy", categories: ["Travel & Hospitality"] },
  { slug: "turo", name: "Turo", categories: ["Travel & Hospitality"] },
];

export const COMPANY_CATEGORIES = [
  ...new Set(GREENHOUSE_COMPANIES.flatMap((c) => c.categories)),
].sort();
