// A large set of US higher ed institutions (universities, colleges, community, trade/tech, private, state)
// Each entry: { slug, name, categories: ["Higher Education"] }
export const HIGHERED_GREENHOUSE_COMPANIES = [
  { slug: "harvard", name: "Harvard University", categories: ["Higher Education"] },
  { slug: "mit", name: "Massachusetts Institute of Technology", categories: ["Higher Education"] },
  { slug: "stanford", name: "Stanford University", categories: ["Higher Education"] },
  { slug: "berkeley", name: "UC Berkeley", categories: ["Higher Education"] },
  { slug: "ucla", name: "UCLA", categories: ["Higher Education"] },
  { slug: "usc", name: "University of Southern California", categories: ["Higher Education"] },
  { slug: "nyu", name: "New York University", categories: ["Higher Education"] },
  { slug: "columbia", name: "Columbia University", categories: ["Higher Education"] },
  { slug: "princeton", name: "Princeton University", categories: ["Higher Education"] },
  { slug: "yale", name: "Yale University", categories: ["Higher Education"] },
  { slug: "uchicago", name: "University of Chicago", categories: ["Higher Education"] },
  { slug: "duke", name: "Duke University", categories: ["Higher Education"] },
  { slug: "northwestern", name: "Northwestern University", categories: ["Higher Education"] },
  { slug: "umich", name: "University of Michigan", categories: ["Higher Education"] },
  { slug: "utexas", name: "University of Texas at Austin", categories: ["Higher Education"] },
  { slug: "psu", name: "Penn State University", categories: ["Higher Education"] },
  { slug: "ohiostate", name: "Ohio State University", categories: ["Higher Education"] },
  { slug: "uflorida", name: "University of Florida", categories: ["Higher Education"] },
  { slug: "uminn", name: "University of Minnesota", categories: ["Higher Education"] },
  { slug: "uwashington", name: "University of Washington", categories: ["Higher Education"] },
  { slug: "arizona-state", name: "Arizona State University", categories: ["Higher Education"] },
  { slug: "georgia-tech", name: "Georgia Tech", categories: ["Higher Education"] },
  { slug: "caltech", name: "Caltech", categories: ["Higher Education"] },
  { slug: "rice", name: "Rice University", categories: ["Higher Education"] },
  { slug: "cmu", name: "Carnegie Mellon University", categories: ["Higher Education"] },
  { slug: "unc", name: "UNC Chapel Hill", categories: ["Higher Education"] },
  { slug: "purdue", name: "Purdue University", categories: ["Higher Education"] },
  { slug: "rutgers", name: "Rutgers University", categories: ["Higher Education"] },
  { slug: "uconn", name: "University of Connecticut", categories: ["Higher Education"] },
  { slug: "umass", name: "UMass Amherst", categories: ["Higher Education"] },
  { slug: "suny", name: "SUNY System", categories: ["Higher Education"] },
  { slug: "cuny", name: "CUNY System", categories: ["Higher Education"] },
  { slug: "miami-dade", name: "Miami Dade College", categories: ["Higher Education"] },
  { slug: "valencia", name: "Valencia College", categories: ["Higher Education"] },
  { slug: "santa-monica", name: "Santa Monica College", categories: ["Higher Education"] },
  { slug: "austin-comm", name: "Austin Community College", categories: ["Higher Education"] },
  { slug: "lincoln-tech", name: "Lincoln Tech", categories: ["Higher Education"] },
  { slug: "univ-phoenix", name: "University of Phoenix", categories: ["Higher Education"] },
  { slug: "devry", name: "DeVry University", categories: ["Higher Education"] },
  { slug: "fullsail", name: "Full Sail University", categories: ["Higher Education"] },
  { slug: "drexel", name: "Drexel University", categories: ["Higher Education"] },
  { slug: "bostonu", name: "Boston University", categories: ["Higher Education"] },
  { slug: "emory", name: "Emory University", categories: ["Higher Education"] },
  { slug: "georgetown", name: "Georgetown University", categories: ["Higher Education"] },
  { slug: "vanderbilt", name: "Vanderbilt University", categories: ["Higher Education"] },
  { slug: "notredame", name: "University of Notre Dame", categories: ["Higher Education"] },
  { slug: "wakeforest", name: "Wake Forest University", categories: ["Higher Education"] },
  { slug: "wellesley", name: "Wellesley College", categories: ["Higher Education"] },
  { slug: "smith", name: "Smith College", categories: ["Higher Education"] },
  { slug: "oberlin", name: "Oberlin College", categories: ["Higher Education"] },
  { slug: "pomona", name: "Pomona College", categories: ["Higher Education"] },
  { slug: "swarthmore", name: "Swarthmore College", categories: ["Higher Education"] },
  { slug: "amherst", name: "Amherst College", categories: ["Higher Education"] },
  { slug: "williams", name: "Williams College", categories: ["Higher Education"] },
  { slug: "middlebury", name: "Middlebury College", categories: ["Higher Education"] },
  { slug: "haverford", name: "Haverford College", categories: ["Higher Education"] },
  { slug: "grinnell", name: "Grinnell College", categories: ["Higher Education"] },
  { slug: "reed", name: "Reed College", categories: ["Higher Education"] },
  { slug: "carleton", name: "Carleton College", categories: ["Higher Education"] },
  { slug: "macalester", name: "Macalester College", categories: ["Higher Education"] },
  { slug: "brynmawr", name: "Bryn Mawr College", categories: ["Higher Education"] },
  { slug: "scripps", name: "Scripps College", categories: ["Higher Education"] },
  { slug: "harvey-mudd", name: "Harvey Mudd College", categories: ["Higher Education"] },
  { slug: "calarts", name: "California Institute of the Arts", categories: ["Higher Education"] },
  { slug: "pratt", name: "Pratt Institute", categories: ["Higher Education"] },
  { slug: "savannah", name: "Savannah College of Art and Design", categories: ["Higher Education"] },
  { slug: "risd", name: "Rhode Island School of Design", categories: ["Higher Education"] },
  { slug: "julliard", name: "The Juilliard School", categories: ["Higher Education"] },
  { slug: "berklee", name: "Berklee College of Music", categories: ["Higher Education"] },
  { slug: "newschool", name: "The New School", categories: ["Higher Education"] },
  { slug: "parsons", name: "Parsons School of Design", categories: ["Higher Education"] },
  { slug: "sva", name: "School of Visual Arts", categories: ["Higher Education"] },
  { slug: "cia", name: "Cleveland Institute of Art", categories: ["Higher Education"] },
  { slug: "ciao", name: "Chicago Institute of Art", categories: ["Higher Education"] },
  { slug: "fit", name: "Fashion Institute of Technology", categories: ["Higher Education"] },
  { slug: "nyfa", name: "New York Film Academy", categories: ["Higher Education"] },
  { slug: "aii", name: "The Art Institutes", categories: ["Higher Education"] },
  { slug: "penn", name: "University of Pennsylvania", categories: ["Higher Education"] },
  { slug: "brown", name: "Brown University", categories: ["Higher Education"] },
  { slug: "dartmouth", name: "Dartmouth College", categories: ["Higher Education"] },
  { slug: "cornell", name: "Cornell University", categories: ["Higher Education"] },
  { slug: "washu", name: "Washington University in St. Louis", categories: ["Higher Education"] },
  { slug: "tufts", name: "Tufts University", categories: ["Higher Education"] },
  { slug: "brandeis", name: "Brandeis University", categories: ["Higher Education"] },
  { slug: "george-washington", name: "George Washington University", categories: ["Higher Education"] },
  { slug: "american", name: "American University", categories: ["Higher Education"] },
  { slug: "syracuse", name: "Syracuse University", categories: ["Higher Education"] },
  { slug: "fordham", name: "Fordham University", categories: ["Higher Education"] },
  { slug: "loyola-chicago", name: "Loyola University Chicago", categories: ["Higher Education"] },
  { slug: "depauw", name: "DePauw University", categories: ["Higher Education"] },
  { slug: "butler", name: "Butler University", categories: ["Higher Education"] },
  { slug: "kenyon", name: "Kenyon College", categories: ["Higher Education"] },
  { slug: "denison", name: "Denison University", categories: ["Higher Education"] },
  { slug: "wooster", name: "College of Wooster", categories: ["Higher Education"] },
  { slug: "wittenberg", name: "Wittenberg University", categories: ["Higher Education"] },
  { slug: "ohio-wesleyan", name: "Ohio Wesleyan University", categories: ["Higher Education"] },
  { slug: "baldwin-wallace", name: "Baldwin Wallace University", categories: ["Higher Education"] },
  { slug: "capital", name: "Capital University", categories: ["Higher Education"] },
  { slug: "otterbein", name: "Otterbein University", categories: ["Higher Education"] },
  { slug: "wheaton", name: "Wheaton College", categories: ["Higher Education"] },
  { slug: "elmhurst", name: "Elmhurst University", categories: ["Higher Education"] },
  { slug: "illinois-wesleyan", name: "Illinois Wesleyan University", categories: ["Higher Education"] },
  { slug: "lake-forest", name: "Lake Forest College", categories: ["Higher Education"] },
  { slug: "lawrence", name: "Lawrence University", categories: ["Higher Education"] },
  { slug: "ripon", name: "Ripon College", categories: ["Higher Education"] },
  { slug: "beloit", name: "Beloit College", categories: ["Higher Education"] },
  { slug: "carroll", name: "Carroll University", categories: ["Higher Education"] },
  { slug: "marquette", name: "Marquette University", categories: ["Higher Education"] },
  { slug: "stolaf", name: "St. Olaf College", categories: ["Higher Education"] },
  { slug: "gustavus", name: "Gustavus Adolphus College", categories: ["Higher Education"] },
  { slug: "hamline", name: "Hamline University", categories: ["Higher Education"] },
  { slug: "macalester", name: "Macalester College", categories: ["Higher Education"] },
  { slug: "stthomas", name: "University of St. Thomas", categories: ["Higher Education"] },
  { slug: "bethel", name: "Bethel University", categories: ["Higher Education"] },
  { slug: "concordia", name: "Concordia College", categories: ["Higher Education"] },
  { slug: "stcloud", name: "St. Cloud State University", categories: ["Higher Education"] },
  { slug: "mankato", name: "Minnesota State University, Mankato", categories: ["Higher Education"] },
  { slug: "winona", name: "Winona State University", categories: ["Higher Education"] },
  { slug: "bemidji", name: "Bemidji State University", categories: ["Higher Education"] },
  { slug: "moorhead", name: "Minnesota State University Moorhead", categories: ["Higher Education"] },
  { slug: "metrostate", name: "Metropolitan State University", categories: ["Higher Education"] },
  { slug: "stcloud-tech", name: "St. Cloud Technical & Community College", categories: ["Higher Education"] },
  { slug: "century", name: "Century College", categories: ["Higher Education"] },
  { slug: "normandale", name: "Normandale Community College", categories: ["Higher Education"] },
  { slug: "anokatech", name: "Anoka Technical College", categories: ["Higher Education"] },
  { slug: "anokaramsey", name: "Anoka-Ramsey Community College", categories: ["Higher Education"] },
  { slug: "dakotatech", name: "Dakota County Technical College", categories: ["Higher Education"] },
  { slug: "inverhills", name: "Inver Hills Community College", categories: ["Higher Education"] },
  { slug: "minneapolis-comm", name: "Minneapolis Community & Technical College", categories: ["Higher Education"] },
  { slug: "northhennepin", name: "North Hennepin Community College", categories: ["Higher Education"] },
  { slug: "riverland", name: "Riverland Community College", categories: ["Higher Education"] },
  { slug: "rochester", name: "Rochester Community & Technical College", categories: ["Higher Education"] },
  { slug: "southcentral", name: "South Central College", categories: ["Higher Education"] },
  { slug: "vermilion", name: "Vermilion Community College", categories: ["Higher Education"] },
  { slug: "alextech", name: "Alexandria Technical & Community College", categories: ["Higher Education"] },
  { slug: "central-lakes", name: "Central Lakes College", categories: ["Higher Education"] },
  { slug: "pine-tech", name: "Pine Technical & Community College", categories: ["Higher Education"] },
  { slug: "ridgewater", name: "Ridgewater College", categories: ["Higher Education"] },
  { slug: "riverland", name: "Riverland Community College", categories: ["Higher Education"] },
  { slug: "southwest-minnesota", name: "Southwest Minnesota State University", categories: ["Higher Education"] },
  { slug: "winona", name: "Winona State University", categories: ["Higher Education"] },
  { slug: "bemidji", name: "Bemidji State University", categories: ["Higher Education"] },
  { slug: "moorhead", name: "Minnesota State University Moorhead", categories: ["Higher Education"] },
  { slug: "metrostate", name: "Metropolitan State University", categories: ["Higher Education"] },
  { slug: "stcloud-tech", name: "St. Cloud Technical & Community College", categories: ["Higher Education"] },
  { slug: "century", name: "Century College", categories: ["Higher Education"] },
  { slug: "normandale", name: "Normandale Community College", categories: ["Higher Education"] },
  { slug: "anokatech", name: "Anoka Technical College", categories: ["Higher Education"] },
  { slug: "anokaramsey", name: "Anoka-Ramsey Community College", categories: ["Higher Education"] },
  { slug: "dakotatech", name: "Dakota County Technical College", categories: ["Higher Education"] },
  { slug: "inverhills", name: "Inver Hills Community College", categories: ["Higher Education"] },
  { slug: "minneapolis-comm", name: "Minneapolis Community & Technical College", categories: ["Higher Education"] },
  { slug: "northhennepin", name: "North Hennepin Community College", categories: ["Higher Education"] },
  { slug: "riverland", name: "Riverland Community College", categories: ["Higher Education"] },
  { slug: "rochester", name: "Rochester Community & Technical College", categories: ["Higher Education"] },
  { slug: "southcentral", name: "South Central College", categories: ["Higher Education"] },
  { slug: "vermilion", name: "Vermilion Community College", categories: ["Higher Education"] },
  { slug: "alextech", name: "Alexandria Technical & Community College", categories: ["Higher Education"] },
  { slug: "central-lakes", name: "Central Lakes College", categories: ["Higher Education"] },
  { slug: "pine-tech", name: "Pine Technical & Community College", categories: ["Higher Education"] },
  { slug: "ridgewater", name: "Ridgewater College", categories: ["Higher Education"] },
];
